apiVersion: v1alpha1
kind: LinkAliasConfig
name: bond0-m0
selector:
  match: glob("38:05:25:36:ab:*", mac(link.hardware_addr)) && glob("igc", link.driver)
---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links:
  - bond0-m0
bondMode: active-backup
mtu: 1500
addresses:
  - address: 192.168.10.11/24
routes:
  - gateway: 192.168.10.1
