---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name kritika-postgres-credentials
spec:
  refreshInterval: "0"
  target:
    name: *name
    template:
      type: kubernetes.io/basic-auth
      data:
        username: ""
        password: "{{ .password }}"
        uri: "postgres://:{{ .password }}@kritika-postgres-rw.kritika.svc.cluster.local:5432/kritika?sslmode=require&connect_timeout=10"
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: pw
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name kritika-postgres-app
spec:
  refreshInterval: "0"
  target:
    name: *name
    template:
      type: kubernetes.io/basic-auth
      data:
        username: ""
        password: "{{ .password }}"
        uri: "postgres://:{{ .password }}@kritika-postgres-rw.kritika.svc.cluster.local:5432/kritika?sslmode=require&connect_timeout=10"
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: pw
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name kritika-postgres-runner
spec:
  refreshInterval: "0"
  target:
    name: *name
    template:
      type: kubernetes.io/basic-auth
      data:
        username: ""
        password: "{{ .password }}"
        uri: "postgres://:{{ .password }}@kritika-postgres-rw.kritika.svc.cluster.local:5432/kritika?sslmode=require&connect_timeout=10"
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: pw
