---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app minecraft
  namespace: &namespace games
spec:
  components:
    - ../../../../components/kopiur
  interval: 1h
  path: ./kubernetes/apps/games/minecraft/app
  postBuild:
    substitute:
      APP: *app
      KOPIUR_CAPACITY: 20Gi
      KOPIUR_SNAPSHOT_SCHEDULE: "H */6 * * *"
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app minecraft-test
  namespace: &namespace games
spec:
  components:
    - ../../../../components/kopiur
  dependsOn:
    - name: minecraft
  interval: 1h
  path: ./kubernetes/apps/games/minecraft/test
  postBuild:
    substitute:
      APP: *app
      KOPIUR_CAPACITY: 20Gi
      KOPIUR_SNAPSHOT_SCHEDULE: "H */3 * * *"
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
