---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  interval: 1h
  values:
    fullnameOverride: k8s-gateway
    serviceType: LoadBalancer
    service:
      annotations:
        lbipam.cilium.io/ips: "192.168.10.21"
      externalTrafficPolicy: Cluster
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: null
        memory: 128Mi
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
    servers:
      - zones:
          - zone: .
            use_tcp: true
        port: 1053
        servicePort: 53
        plugins:
          - name: k8s_gateway
            parameters: "${SECRET_DOMAIN}"
            configBlock: |-
              apex k8s-gateway.network
              ttl 1
              resources HTTPRoute Service
          - name: log
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . /etc/resolv.conf
          - name: loop
          - name: reload
          - name: loadbalance
