---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: libredb-studio
spec:
  chartRef:
    kind: OCIRepository
    name: libredb-studio
  interval: 1h
  values:
    route:
      main:
        enabled: true
        hostnames:
          - libredb.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
