---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.envoyproxy.io/httproutefilter_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: static-401
spec:
  directResponse:
    body:
      inline: |
        {
          "error": "authentication_required"
        }
      type: Inline
    contentType: application/json
    statusCode: 401
