# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.5/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mc-restarter
  namespace: games
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          activeDeadlineSeconds: 300
          containers:
            - args:
                - |
                  NAMESPACE=games
                  TARGET="deployment/minecraft"

                  echo "Starting rolling restart of $TARGET at $(date)"

                  # This command updates an annotation, which triggers a controlled
                  # rolling update on the Deployment.
                  kubectl rollout restart $TARGET

                  echo "Restart initiated. Deployment will manage the graceful shutdown."
              command: ["/bin/sh", "-c"]
              image: ghcr.io/faustvii/containers/playground:main@sha256:0dda6c6aefec451537dcb5f3ea0ad320e87ad284bf5a65008eec7449cd11b405
              name: mc-restarter
              resources:
                requests:
                  cpu: 10m
              securityContext:
                allowPrivilegeEscalation: false
                capabilities: { drop: ["ALL"] }
                readOnlyRootFilesystem: true
          restartPolicy: Never
          securityContext:
            fsGroup: 65532
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
          serviceAccountName: mc-restarter-sa
  schedule: "15 3 * * *" # Runs every day at 3:15 AM
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-restarter-sa
  namespace: games
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mc-restarter
  namespace: games
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mc-restarter-binding
  namespace: games
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mc-restarter
subjects:
  - kind: ServiceAccount
    name: mc-restarter-sa
    namespace: games
