---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
spec:
  chartRef:
    kind: OCIRepository
    name: descheduler
  interval: 1h
  values:
    deschedulerPolicy:
      metricsProviders:
        - source: KubernetesMetrics
      profiles:
        - name: Default
          pluginConfig:
            - args:
                podProtections:
                  defaultDisabled:
                    - FailedBarePods
                    - SystemCriticalPods
              name: DefaultEvictor
            - args:
                metricsUtilization:
                  source: KubernetesMetrics
                targetThresholds:
                  cpu: 50
                  memory: 50
                  pods: 50
                thresholds:
                  cpu: 20
                  memory: 20
                  pods: 20
              name: LowNodeUtilization
            - args:
                excludeOwnerKinds:
                  - Job
                includingInitContainers: true
                minPodLifetimeSeconds: 1800
                reasons:
                  - ContainerStatusUnknown
                  - NodeAffinity
                  - NodeShutdown
                  - Terminated
                  - UnexpectedAdmissionError
              name: RemoveFailedPods
            - name: RemovePodsViolatingInterPodAntiAffinity
            - args:
                nodeAffinityType:
                  - requiredDuringSchedulingIgnoredDuringExecution
              name: RemovePodsViolatingNodeAffinity
            - name: RemovePodsViolatingNodeTaints
            - name: RemovePodsViolatingTopologySpreadConstraint
          plugins:
            balance:
              enabled:
                - LowNodeUtilization
                - RemovePodsViolatingTopologySpreadConstraint
            deschedule:
              enabled:
                - RemoveFailedPods
                - RemovePodsViolatingInterPodAntiAffinity
                - RemovePodsViolatingNodeAffinity
                - RemovePodsViolatingNodeTaints
    deschedulerPolicyAPIVersion: descheduler/v1alpha2
    kind: Deployment
    leaderElection:
      enabled: true
    service:
      enabled: true
    serviceMonitor:
      enabled: true
