---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriatraces-tempo
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    uid: tempo
    type: tempo
    name: tempo
    access: proxy
    url: http://vtsingle-vt.observability.svc.cluster.local:10428/select/tempo
    jsonData:
      serviceMap:
        datasourceUid: prometheus
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: "-2m"
        spanEndTimeShift: "2m"
        tags:
          - key: service.name
            value: service
