apiVersion: v1alpha1
kind: KubeletConfig
defaultRuntimeSeccompProfileEnabled: true
config:
  maxPods: 250
  serializeImagePulls: false
  imageGCHighThresholdPercent: 70
  imageGCLowThresholdPercent: 50
  imageMinimumGCAge: "48h"
  imageMaximumGCAge: "168h"
---
apiVersion: v1alpha1
kind: KubeNodeConfig
nodeIP:
  validSubnets:
    - 192.168.10.0/24
