---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/main/dist/schemas/pocketidinstance_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDInstance
metadata:
  name: pocket-id
spec:
  analyticsDisabled: true
  appUrl: https://idm.${SECRET_DOMAIN}
  databaseUrl:
    valueFrom:
      secretKeyRef:
        key: uri
        name: pocket-id-postgres
  encryptionKey:
    valueFrom:
      secretKeyRef:
        key: ENCRYPTION_KEY
        name: pocket-id-secret
  fileBackend: database
  image: ghcr.io/pocket-id/pocket-id:v2.13.0-distroless@sha256:ccb590169770feb5b23ba16d49386514a2c26a77e95bb687b442ae09f17c15da
  metrics:
    enabled: true
  route:
    enabled: true
    parentRefs:
      - name: envoy-external
        namespace: network
  ui:
    appName: "FaustID"
    homePageUrl: /settings/apps
  userManagement:
    allowOwnAccountEdit: true
    allowUserSignups: "disabled"
  versionCheckDisabled: true
