---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/main/dist/schemas/pocketidinstance_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDInstance
metadata:
  name: pocket-id
spec:
  analyticsDisabled: true
  appUrl: https://idm.${SECRET_DOMAIN}
  databaseUrl:
    valueFrom:
      secretKeyRef:
        key: uri
        name: pocket-id-postgres
  encryptionKey:
    valueFrom:
      secretKeyRef:
        key: ENCRYPTION_KEY
        name: pocket-id-secret
  fileBackend: database
  image: ghcr.io/pocket-id/pocket-id:v2.14.0-distroless@sha256:e0f83a42a78d0759b6d2d8c7380ef0fa8a4c95dfa01ad88740a073ae9cc4ba94
  metrics:
    enabled: true
  route:
    enabled: true
    parentRefs:
      - name: envoy-external
        namespace: network
  ui:
    appName: "FaustID"
    homePageUrl: /settings/apps
  userManagement:
    allowOwnAccountEdit: true
    allowUserSignups: "disabled"
  versionCheckDisabled: true
