---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/main/dist/schemas/pocketiduser_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUser
metadata:
  name: foshu
  annotations:
    pocketid.internal/delete-from-pocket-id: "true"
spec:
  displayName:
    value: foshu
  email:
    value: foshu@${SECRET_DOMAIN}
  firstName:
    value: foshu
  locale: en
  username:
    value: foshu
