---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/opentelemetry.io/opentelemetrycollector_v1beta1.json
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  config:

    exporters:
      debug: {}
      otlp_grpc:
        compression: gzip
        endpoint: vtsingle-vt-otel.observability.svc.cluster.local:4317
        tls:
          insecure: true
      otlp_http:
        compression: gzip
        encoding: proto
        logs_endpoint: http://vlsingle-vl.observability.svc.cluster.local:9428/insert/opentelemetry/v1/logs
        metrics_endpoint: http://vmsingle-vmks.observability.svc.cluster.local:8428/opentelemetry/v1/metrics

    processors:
      deltatocumulative:
        max_stale: 5m
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "[::]:4317"
          http:
            endpoint: "[::]:4318"

    service:
      pipelines:
        logs:
          exporters: [otlp_http]
          processors: [memory_limiter]
          receivers: [otlp]
        metrics:
          exporters: [otlp_http]
          processors: [memory_limiter, deltatocumulative]
          receivers: [otlp]
        traces:
          exporters: [otlp_grpc]
          processors: [memory_limiter]
          receivers: [otlp]
