apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:GIOS+9Pkiyw9uY3gPvkgWiv1scTaymoUtxh93pjIJV+P/7msMm3KUQ==,iv:uqxJmrOj5If6HYBNXkX+H3y5vDrzJ/R9bWY9uwn1bfw=,tag:EejSjVbCH4SqhafwQsRH6w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHVjNUREUEVG
        djMxY3VMR1FKaHBNSnJ2cDRiWUcxUGdCWnAzOTlya1RXNGdrSHRJdHZVekFqSmw2
        dGx1R2Y5VG45TEx3NjdZQkk4bFR0WXFwbURpMTRhWm14eDhFNmMrK1BkY2F3RFdQ
        dE5UcDB0dWs4YUJSTFRzK1phTjFhYUVnRXhUbVNqWmhjaXJEWlIyZHhXUnp3SUdY
        emt0MThhOFNLcE9hV04wWXdxY2FEZk1CeGROWHAveTlzaHpxNU45Qks3MDhIenFi
        MTRMT05XWklKcGIxUkpBeHgrSGlZY3VqNkNQZ3hVSmFwQmFzVmc5YlNSMU53TEdx
        UEZsQWl6eC9INXNVSmY0YmRZVzdiWU8rNnovZmFHRmxDdHZsVExYc25SbDFhWStK
        S05xVEs4Qnhpc3dlSVpidlM1VG9ycngxWndTaThjOW1NSGpHaDJvNkpRRkJab2FO
        V1RkSkt6Z2hHRnc3VEh3OVYrY0g1OGQyN2JUaHdDTnhrNS9YdjcxS0lpbmg0NnhJ
        RnQwVDFjYXlpbVBKNGdWYmg5NFdMekxzQjJhZUd1ZFQ0Y3NYQXlkSGN3eUNhRVFp
        Y1BlUlNxM09FVHc2QXNtL0cwY1E1OHNLRGZJQ0JvVm5SQWR4aklUditKdy82eWsv
        bFc4K0xlc3JXVU1aOGZqc1Z3emkxZGpqWTRZWHZZOEE1bi9QWjM3QkFFZzVYdngy
        dTNqeS9Hby9vakplbXYyMWx0ajA0REo1ekVmK0RYenk0bThEaGZvWGFQWTd3ZmJI
        cEJjYVF5TTNrTWUySEZZWlJKYjdWaDNpQm5Ta28xNTBhTUFZaFRUaWJTdjJRdmlj
        WUtIZElJMTJZQTlPWmxkTnNacE8zNEQycjlURmxJemFGbk1WNFZPOWc1VVlmRW1X
        RzFzUHNPaS9kVXB2Y3NIODk3UXJoTlkxYVVtejF2eHFnM09uVUtoWW9TWnlHMklP
        b3l6dm4wZWJIQmc2UGxCT1N6MDlLcmJCcFZSQ1dsWUtaa25ZbURTTTVTOHl3bGxt
        UTZJQS8rajV0UjliSDVNN1UvOWcwRHQ2S3FCN2JOLy9oYXpNbmhFS1ZBRTE0aE9y
        K1JWMEtpTTdoY1pJTC96V2NsUWxnZXI4NWNmancxdXA3THU2VTFtYnRDSnNjRFRZ
        R05OL1ZWekpCY2w3SWhsOGVvOWhtQ3FFSkl6U2prUnlEbEpLckdvaGFEdmplUWtO
        Q3BJZERscGRkV1BFMUZnRlgwYkNpa2lmdmNzNzIycUM1MHJINEJ1VGgwZkNjZGkx
        dlpmbGMvd09jaFloc1NpM2h0RVVZYVlyaG93Z015Q0cwYktWLzJ5OGxKZ1JzcGJG
        TUxyOVRsK3FDSVJISCtLNmt6NW81T0hZVDR3T0V6cTFhMm5BdEVQRXZmc0RuQ0xl
        WHQ4REFmZWhDYzBIdFJUWEd2YVdKK0ZmRy9qUzJxUkpzZ0dycStlODNhL2lpMFpm
        SE00NWNDWXZyODlnUlVJVzVJMjBiUmllcWxEb2dRMXNtMnY1YnA4TnhKMG9hdzhM
        U3BwK2QreVE5L1cvVkxBbTFHV0hCcWVsWGhKWm9kKzdPVWlPOS85V2dvdnhDUm5u
        aUo2MXpLVmtUQVpRU0puTFNEUml1V0hocUZ2d3g3K0dmN3VpNEIyemN3WkZEbXN0
        TXhmYzNDNDd5K2RGY1VtSmlCNnNtMWZVYjZ3QjN1ZUVwQ3ZrWVQxQ054KzVYQkJm
        aVFFMG9zVUNBNE9SSFRsK1N2MnNrbWRua2dtK3V1MkJDMUs1T2hLQ01SaVR5L3RR
        dUNUS1h3dzI0TUFJRFdtTy82V2pUdmp6TzNTU29OeXByYjhOdTA2cGhtdUJLcjdh
        NmFRa21hdnlYem5PZ1NGeks1RDBGbjRkOGtiaTd5L3Zkb0d4Vk9pOXdZVVZMZW1I
        Nk1iYUMwV1B5Q2ZmQkdyTUxuVHBBYUVwU0hJVGwvT1lLcm5DWFRpMkpwclZZUQpu
        OG8xbGhHeldydW9WQzdHWHZSbkhNemtoMWN3OUtwSW90a1RmTXdBdGZZCi0tLSBh
        STl4eG96TmFtbWRXK3ozQ2JCU0l5RkxDbjJ0ZUIzOW1UQzZwemR1bmtZCpJFt9eD
        UWZ0STCstuTKD/EyjyTmwZL2RfUizUQ/7EFo4zAxi6tzSoTXrAWiD8cCbNQiSzWo
        01yqZ9V6FUIm+mc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-08T16:10:50Z"
  mac: ENC[AES256_GCM,data:WaXK/I0RlVSFF08ub4XZ/qyR9gylpt6/KHjo/tgylrGsadBR6Jew0qCaZJy26LR7xNy7hKJHtVUb+/UJNTLZksJ/chqJsYksaGFs71EsyiwnIBxCn7NjnVYO67DRhdNJ1zfDlr8xtMJPnmNcryWPG6MqMT/F/UQanTw4XjadNGY=,iv:Cl7MCrdfpg2BL9P4X5VGfG9Fl95Wl03TnRKe4yAxxyE=,tag:FbK1oxA7gFtEM/PGk7Kj1Q==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
