apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:GIOS+9Pkiyw9uY3gPvkgWiv1scTaymoUtxh93pjIJV+P/7msMm3KUQ==,iv:uqxJmrOj5If6HYBNXkX+H3y5vDrzJ/R9bWY9uwn1bfw=,tag:EejSjVbCH4SqhafwQsRH6w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL2JQUGg5aWpJSzA3a3BO
        Yk5nSU9Pc3J2UVZ1VTNFWU4rb2p1eHFLbm5BCmF6SUhMWkNzN1Z1U0NpMjREWTlm
        Q3g1YjVWZFBhenluRjU4R016K1dNU0kKLS0tIDFTTHpRZlRCSjZkY3NwUGVsTkp0
        SlYrOXJLK1grblVKTHlHWHVGV3liUVkKkzP5waZa9R4QLngEsR/Gte/HTL4/gA94
        kHAk1Nc4wl5khl5ZiiS9GyWn5leX4nqj6bRKLcEz3x0uY979n5EPvg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGtINVlKMHpP
        M1VyTnlBTm5PQ1lsQytTV2w1NkVhdXRlSFBkSGhVcEJDb2hRL2cvL3F2WUg2WTB6
        ak9GdFFEVUk5bWxCRnpXWXZuWTk2OUMrNm5CWUFmV2YxMXAwdTJVYWVzcnFuaml4
        SFpSRDk0dXg0dzZDQ0tZVTlGZ01leVcwNHB3RXVrWVFPdENPc1M2SW0zbkROZlgv
        YkIzVE5xa29kL2s4VVN2NGo0TjB3OXZpcGswRHM5eFFtQU1LQXVxeDRnay9CSVFX
        bVVzZkZ4ZURKTTBKbEpFa1BhaG8yMFZRYmdIZWpqYWtCNGZhL3hGT2YzVXVqUSs2
        SlQ1a0xRWTB1RzJlV3FFM3BnekFCV21QdndjY2IzY0N3d3lRUmdkMkJrMWFzNTVN
        NGJxaE5PV2UxUVRjVWlWTkR3Yk1KZVg2SThQSkNjTnE0amxSd3BBamMybzR2dmds
        ci9NcGh0Qys5U0RVWEI4bHlTUjhNZmlsSXdNcm5xazdjcHEwcG0vRnY4YURCbkUx
        UTg3VGhvam84VHV0cHp1NHo1eldaWjFqeVFJdnY3eFRnY2VROGdGR28vOUdhQ0kx
        WGNKVFIyTTQxU3hGakhMZStWSm9INkpnNDRjOENGS3JVcWF2NTZvdURhT1dDRFo2
        Y0d4S3o5R0tCMEJPbWF4clM4S2c1S0JpZ0dnN09TVWJrbzBrbHNMSWJTVTZFVXF4
        ZHZ3VzVQd2FYTkljWHpiNXpTNlJhWC9nZWJrcmY4dXM3ODBJbXZkQWNJcURwaVZz
        ZGFPRVpCL3pxZzh4STRjM0tFbjNRL1NxRml6dERIczJLcS84VTFadGVPZDJOQ1Zw
        aFovTElzM0htM2ZXa2ZaZVBnSW9uajJqMHVYSDYyeFk1QXBKTEFnUExtZ1Z6cmI1
        RENvc3VmT0krb2p0Z3dXT2J4MGN2V2xuaG10R1h0MWJTQWVZVXhDeTVZWVNBMlVo
        dUpYdm04TzZDOWhoMXFQMzhUQTdYY1JRMEJ4cTBJdGxuMmJpdmpnTmlZSlJLM3JB
        aCt6M2ZrZEMvMlJHYjNuaWR1a0pzU1FaZ2xTbldWeFJGa01SSjM2NHJsQzYxYzRi
        L29FN212T1NjWG12MkZDRVFZRWpneFQrR0VKdnBJbFA2K3pnVytsc2FWbUhLYVBI
        T1hIcmtmSEFoanU2Q1R0WHQ1UEhWbEladDhEUytLK3FLSXg2U1FBZ3hyYzFRTjVp
        eWQwQ2NUWnQzaFNRNG5abEhYcHFlSGk3bnp0aUZQeWsyOGpVSVNCNm50ejF4aXl5
        NkhEU0Q2aHRCSEpwelNQSm9ZMFVac2pIZUhuSHA4WFNHL1V4c1NXWW5DQjFnRUJB
        ZTBkU2g0WDRDc01kTEw1blBwclRGbm5abjlKMTc4Y05BWWxxUVFZUVJmaHpMUGxx
        bWVoaXk4Mmo1RVFXbU9PWXdTQklHam5janRGR1lkbjB1OWRlRWlzTERGMURGQzVm
        aERZRVplTE9sMW0vclN1T3hkTGkyaDJIbm1YTnFpRWgybUl1QnhETnpPWmFxQnh3
        akphMXVRSytYVmJVOGVkWGxTRUo0d0twMXNBNy9mNkJGKzlkSVJPTy9hK0U2a3lZ
        YWQrT3J0VXhDM0lkQzNKbzlxNC9YL2ZpQjhOa3ZBa3NJT0pQaHkwZk1YS25VYXoy
        alFrK2hheDl1bHVaTFAycktZdk56UzJEdHZPTWxXV0V6TVp5TWg2YkVPUlp6R2c5
        UXlDR3BhdFp0NjFMM1N5amwrd0N2NktSWFBpY1Z2WkJaRHZpUUhEZStwb25oRmdU
        Q0dZRURvZHZjRmJGZjJzYnRqb0ZZWGxnZVNuV2VTcW9PbTN1RklXeVRkOCsxNGg1
        S3JzYkFoN1VKcDdOaGlFVnYzVW5wbkRqS2hxam9qdWRCMnorUEJrU0QrNWlvbWlU
        M2FvZ3Qxc3M1akFiNzNjRlhVZkI2WUp2M0txR3VWRURzallMVWQ0QmdENE1Gdwpw
        UlJnTTNMZkJvaERkN0VSbTBNY1p1VVh3Z0xrYmdXLzdqZ0NxdUhtSTBzCi0tLSA4
        WS9MMDIvMTFwbVFUdnVvaDZzeUNxUEozQVk1UzFYSFpkUzRGTlRqM05FChjxv6c+
        8Z3Xhjv1wjDr/QD9gQoGxUIx2zqBppH+yP+7xFbaU6GGaWgDGnjccGa1gCEw1kWa
        cIWy0XTDVLkU+iw=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-08T16:10:50Z"
  mac: ENC[AES256_GCM,data:WaXK/I0RlVSFF08ub4XZ/qyR9gylpt6/KHjo/tgylrGsadBR6Jew0qCaZJy26LR7xNy7hKJHtVUb+/UJNTLZksJ/chqJsYksaGFs71EsyiwnIBxCn7NjnVYO67DRhdNJ1zfDlr8xtMJPnmNcryWPG6MqMT/F/UQanTw4XjadNGY=,iv:Cl7MCrdfpg2BL9P4X5VGfG9Fl95Wl03TnRKe4yAxxyE=,tag:FbK1oxA7gFtEM/PGk7Kj1Q==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
