---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crucix
spec:
  chartRef:
    kind: OCIRepository
    name: crucix
  interval: 1h
  values:
    controllers:
      crucix:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/calesthio/crucix
              tag: latest@sha256:a9a201c774e665f16e379eb8f8887ea7548dce4ad0a0daa8ac92935058e70b4a
            env:
              TZ: "${TZ}"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: &port 3117
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      tmp:
        type: emptyDir
      data:
        enabled: true
        size: 1Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /app/runs
          - path: /app/runs/memory

    service:
      app:
        ports:
          http:
            port: *port
          smtp:
            port: 1025
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
