
attachment-cache-dir: /cache/attachments

auth-default-access: deny-all
auth-file: /data/user.db
base-url: https://${APP}.${SECRET_DOMAIN}
behind-proxy: true
cache-file: /cache/cache.db
enable-metrics: true

listen-http: "[::]:8080"
log-format: json

log-level: info
metrics-listen-http: "[::]:9090"
