apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Z1zDkLuXHaF+IB4=,iv:7drdn19GpYDhlx8kEpTRVO/cGZr83h/duj59H+3vwXo=,tag:DKLTk4LPJgfwUxyizKgimA==,type:str]
  SECRET_DOMAIN_1: ENC[AES256_GCM,data:T1q82NPU+A5l2dg=,iv:IKMiw8AJqKfSCTgRDtm/txbQedJ9z7WHnh/d92XlU9w=,tag:EGwvZiFUbSr+CLr35mpnEA==,type:str]
  TZ: ENC[AES256_GCM,data:TxjOp+Anij0FmPYyu9RIa+A=,iv:TSVAUmPR+lCyzsD5Eh+VcF0KP7Sb4I7h/j1W3RGnJ7Y=,tag:xceI1dQgDShoTgGrwZ4rJQ==,type:str]
  NFS_SERVER_IP: ENC[AES256_GCM,data:Dz5FYwkfXRyg4jJs,iv:AJZxQCIjJDKtsVHy02sqhuMjJQxFQSv3DSobgkp2TQ4=,tag:txA11aYE0/Uqmf+PhTSsQg==,type:str]
  NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:bof6o3l6t3QYa7A5XdWsZm1TmQTvg1phclg5xA==,iv:zhACCbbugIjesEHYf7Q0Qw8Q8jtZRpzTRPvlMsP/mLU=,tag:aX5JpJlZORKhuaPvTF7DqA==,type:str]
  NFS_PATH_MEDIA: ENC[AES256_GCM,data:Dqw+LkOsE9r6TEIVnSuXcQ==,iv:/p3CcCg6uPwEVlRkf+5aE40VjU1Q0E8x6KLGCUT6MtM=,tag:KMm3ttYjfjJeQcXg6H4iqA==,type:str]
  NFS_PATH_PLEXMEDIA: ENC[AES256_GCM,data:L3bxToIhgBTjtYGcCKtFAaMIVqAF26CcVxM=,iv:6rFxYh7mAJdkRteUvgko7YXtmqxhCKqOLSTVmlxASB8=,tag:QBdTrxAevdZtVEqReQnPiw==,type:str]
  NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:z5yOe773RbguDMltu5xRcbCMczWfhdm00lMUsYbwLclh,iv:iJQtVrWIXmFkrQL+rOo9jeON+Ms9FvkYgP9/YMgVYrc=,tag:0ZE97hAiOT7d/nx26KGVQg==,type:str]
  NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:CDaRY4y1nK42NoVdo8X/74VWTS4yOgBpFosVWArCxnWg,iv:pH25Qw/9ZzBsv+G0Dij5XfyyDIx0aZNRWjcOS0QIfPs=,tag:L9Iw5yFV0uBnAFJQ1Z4WrQ==,type:str]
  NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:LiuC4FOjmxYSKsCRiWNhoezcdxcMQses0eKkN6FJuf4=,iv:Pvh3h4w5oeLx7780bpKPUZbvXmrAIVHpOCijwxD0Amw=,tag:TLqLYkJ8nntQbKok2fprcQ==,type:str]
  NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:svIRqRq+jt8+cwhrooSjUn/FnIhNtA==,iv:tgQH1+Zss4xkKFoAeG3rF5iCEads7RiR+F6p7bQ7utE=,tag:Gic7C+p+Y5OFdVqz386OEQ==,type:str]
  NFS_PATH_CALIBREAUTOMATED_INGEST: ENC[AES256_GCM,data:xTyTjFQM7kIZpETxU7mlWp7ubdJkbhVOpvF4jB1YcYaXxY65YV2cI1pVlJqvg4DZ8MwW,iv:nyvl1Lyrpt+GphpM/NweCOTNOpDbDOmho4COs8vY/+A=,tag:dpeuKIFo+nh/ArToOPEuhA==,type:str]
  NFS_PATH_CALIBREAUTOMATED_LIB: ENC[AES256_GCM,data:lY8DZHihaw/zTETT2l7uGhsXZPTZ4VGAKxUM9js5k+vk7kWOP1A/yyf09gKgHuJVy87Nbw==,iv:IEZsBLukgnHW4LO70Hh8wjlwy+frgDTxXMlMuB9Y8DY=,tag:5pJXH6w/z2FtHeYxAsKUNQ==,type:str]
  NFS_PATH_NEXTCLOUD: ENC[AES256_GCM,data:JrK+QTA32C6jXrfzJJCVEH/Alrn4gA==,iv:HuOuTyZu9rjqj34SZKXej2ShiwPrFIHfSC7bosZbm0s=,tag:JqfoosjHFUhytZ07NfA89g==,type:str]
  NFS_PATH_K8S: ENC[AES256_GCM,data:3+atavmBtD/OdKbS9h3BJROODRh9lMUO,iv:GDhYRb2JAvCmImZv1OZa7bKUIdN0WguDzbRQ+rqtkPA=,tag:CSP3WqpTqgbaOo8MHZ+ukA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGVWb2dXZVNs
        b0YzSll3eDVISW4xNXhyUTlqczdXd0RVckdCSWRRL1FjSEx2L2phQzAraDgrMlhD
        L1BlY0ZqNXc1eTBqTXpRYTBrWHd3VWxlMk1QYlFnK3lIbFFBMFVtUXJUL1R0blUz
        YWk0ZUxqWW5NMEJ1VEJuSS9ZdjV5SnlENGxZdjZkbzhQZ3I0eHlGd2ZwZTJOZjJR
        ZzEzRE5LM2E5aW9QbEJ2QmNKZ2hRWFZhOFAxN3ZObTJxY3BmZWxaZGJOZWxzbUZs
        WTdSQm9sUmtjcy9Vd1lnOTBLb2FzMmVrbUpadXJGM096Y1BhR0tTSTJuQkllenV0
        VHlnbk5lSFN0WnNWaUtjVVZKa1Q5a1llQWMxWnUrR3VDK0kzcmc2TlhEK25WM2t1
        UDlFZEtjbG1BOTltUnBJZ1VoSlVwdlFmaG5ycDdhc1ZUZTBuUUVkUHd2ZjJESEpE
        bjFGL1BJRkVRdm9xbDQwWlI1QjgxLzYvSU5UTjc0d20rdnRXSnNTNU9lUE1IYUhI
        bGhjcXlYRlRDeEF6ZFRHU1IyUEJiZzVoZFlUREZqRGFVZ1Z1ZDdmSUQvMmNpNm1E
        MW14ZGJ3SlA0UHpwOHIxeUhHTWhXdFJ5d3pLTG0yYUl2T05XWEsvTGZsVHU2QUNJ
        ZUIzYXdUNXZxamlaeU9kUTFjNDR0NWkzU1FybDNwdFdOWFNLUk9Za1BYTDBqamdO
        MUE1RFJZelYwU2pMdENaNXNCOGJ1NEI2YTllcDdWbVNEVUxhR294NkgwazJLMHpN
        R2NhMG5jRFhyNzVLRDlrMnFjc0FsaWVtUWc2WUhuTUR2Q3VwSktwdlN5dWdqNk1W
        VkxTQjRyTGZXOThMSVNKV0x2YUlXWERJZFBpR0FHcTd0M1BDVUhaclBGcXJUS0Yx
        dG14ckdBd2ptSHJsL0lWQjFhQXorZ1hZWEhVU2s5SGxwamNNS0hHc045RHlHL0dr
        UndMUG9WNkpkSWZIV0I3bzUrQTVhRUsyZS9TTkdNL1kyNWR5Ylo4Tlpra25lTC83
        NUIzTlI2WU1vNHR4K3lzczlnUXpPYkFSaSs3UFVBdW5MR3I2d3l1dkRLTGc4dE1p
        VXVqZERqNXBmNVREekgzYy9iUk00azFKVmZIVWtJK1h5b3VvNkJ1V1ROSU5sUjk4
        VmVvR1ZSSmxtWUMxbndKZlRxK0REaytsbEk5NjNZaTFqT3d2ZUdNcnJvLzFCVGFn
        aHBLSk5vWEtkL042Y2RYd3lZeHBTR0Nkd1ZDWVcvamNmYnovOGVKQkxlUnhSQXB3
        RWZwcmQ4em1kRnh1c2pObG8zZThWQXhybTNnRnRELytSUklEaW9mYnpQaTdRcDRP
        MlNoM29DbVQ4S3czSjBVdGlTNjVxdm9NV0p1QUVaYVQ2b3Ntb005bVNTNnFXMkhv
        QmpHVU5Ud0V3anhZSlF0MGhqMDdYSnR6TEd0MDBxVEdCZE05cHJ4TUxhM1NOTjh3
        S2p5elpkSFplSU5tS1lHQUsxcm5lOVZuNDdIZ2pjRnl0bHpqTjU0UXZjL1RHTmk1
        b0ZiT1ZIdTJ3WisrRTYvZmJiZ0tOSVdDR1ZpbzliMnA3dFE5RjNkMzJjUDNyNXAz
        Z0wzYnJzREhBRWFmeGJENHFrTmdSV1hoV24ycXpnekxRMDNiS0FlM1JYVHhST28x
        NVp5cW9ZVEZ3Z2o5d2dqeitoMHBhdU5BNDl4VmRlL2l0MmhlbmlKSUdNZ2V0N253
        RHBvTXVwSS84S0l5QUlLMnZBTVRVTCt3Z3RSc2gvbjkzZEJKZXk4VmdlSzZQVUtG
        NUtIcGJzN25uZmVlZitDZTJxaGo0cEtMVEZCT0N2UWJDVFh3V1ZONFlPRGQyYm11
        STV6RXNiWHY3ajNldS9JNmVPSGV0ZXczemJRY215TDFJZGlVYVorTEh6VGVEMFBT
        UFg4ckZCbTJ4dlpLNm1xMi9oVVFVOFZXamNGNjMvY29CbXRYVUtBYWk0dUxGdwo0
        YmVZdU1GR1h2Nm5oOWR5L2MvNjJCWnBKSkF5dDJQT1dGdDNxLy82NDI0Ci0tLSBM
        SWdnSlVVbjJLbENMdkdUSEJrcmE4dXh2NzYwNUIzUnp4TVpTeklKS2R3CjEnKpjm
        kdhH3gYs3JeFkkh7OU3NfGj6bbKspNjPZ+Dg/ZQujN6zU0HJ5IPzTAAPa7hsz9TA
        YuIIB8elmZYwatk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T21:23:42Z"
  mac: ENC[AES256_GCM,data:7Mua2yEjcxBpiT0ox8TyJs316kL6iNbA024UyLqAgZfBrBlmCEu2up/tWj+GD1ymHTXngfe/g0pdBVzeDJi1TcqjqCM+umFS6kQiNs5bjo2cyhPFv3FqfmPJMkS6oDtuX656XAnYmFgenuNjhaeUqyaD96KU8fwhWPY1VxyTuQI=,iv:P5O7jgupt73ZUVa+ftCsZ+QZTj9roAngPC73I/I27U8=,tag:xzMenqnK0qD5nK0B64/dnw==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
