---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app infisical
spec:
  chart:
    spec:
      chart: infisical-standalone
      sourceRef:
        kind: HelmRepository
        name: infisical
      version: 1.10.0
  install:
    remediation:
      retries: 3
  interval: 30m
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: *app

    infisical:
      containerSecurityContext:
        runAsUser: 1000
      image:
        pullPolicy: IfNotPresent
        repository: infisical/infisical
        tag: "v0.165.2"

      podSecurityContext:
        fsGroup: 1000
      replicaCount: 1

    ingress:
      enabled: false
      nginx:
        enabled: false
    nameOverride: *app

    postgresql:
      enabled: false
      useExistingPostgresSecret:
        enabled: true
        existingConnectionStringSecret:
          key: uri
          name: infisical-postgres

    redis:
      enabled: false
