apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: infisical
type: Opaque
stringData:
  AUTH_SECRET: ENC[AES256_GCM,data:PUx57VOgOxcsVebyLTUrFTKRHL+7BHlkQInRm9opSQbjnxRbIIFIM4xrgAs=,iv:D0vqz8Wpy04oJpgvlbcr6GfxW4Rn9eDqJHis8T85dpE=,tag:eGkcSSPXKHE8VlMLL7tkXg==,type:str]
  ENCRYPTION_KEY: ENC[AES256_GCM,data:WuIXRMxME2EuWDVnC6tmKg1++bOc0Nf3LHU6b+1/+AU=,iv:Le8oUYV6JPbms3M4J3wdBni+DzRl0LQ6gnxQre1O+fE=,tag:YDU34BBdEuBpgHHLc/BmIA==,type:str]
  SITE_URL: ENC[AES256_GCM,data:IvXXJTRmGFNAv3T4iBsif4HDZ5WiO/upcsSOKrg1N373xQ==,iv:ETgJcwPW88uRAsfaQez6He8RCW1Ns8Y3lbFTImujk9c=,tag:08X3fHJgkj6vBx0Zk6Nm+g==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:Ad/yQvgqtL3FI0hUXMccNfOZOPh5oCriSxS0+OEHO4Oevy7SiQsCb91O8k9knrL/4nLt,iv:ccd3ogozBJW+pGfIZYCbtFPO7+XyN645G/VepxAKrok=,tag:rB0bvKfbFTqhCdFFoTUx5w==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:EtpyECPbR+jzD/JTu/suOZ2amVvTEZgvBHi1Spb2Kubp,iv:Uij5jcri4uGJWqyzRgqrnIc4IxVeCaEuhyAc5puw6xk=,tag:R7O4ekZYwI51HGh0t9JGeg==,type:str]
  SMTP_FROM_ADDRESS: ENC[AES256_GCM,data:2wTjcEeeUeTUlxsyAU4TfwDSnzdqQXk=,iv:WfAUsJKOqjuJ5hqlH4ixv5DR8/bzO+QeLKopOk9WEpM=,tag:OHpynG2RN5/yzdOFlH+Z7g==,type:str]
  SMTP_FROM_NAME: ENC[AES256_GCM,data:KGbcnMsr6Dsd,iv:5RwS1JgFIy5V2fh+OY6rm+G1wcH3L7BuFTx/z6GX6aU=,tag:lyzV4UucasUFwVWTIQWgWQ==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:drBIZA==,iv:j+D4GjSiubYcJpFbDDYAs7I2OfVSk2O1z+VYzIisl9w=,tag:bsflF24iJ7j5cpTyB3MKhQ==,type:str]
  SMTP_IGNORE_TLS: ENC[AES256_GCM,data:rOioRw==,iv:riWmPffiUxKurBmWdaRw79VGvpIJ/VVDvxvj3XfNM/Q=,tag:7GGn4DC0ir+4GtPWGEb1mw==,type:str]
  SMTP_REQUIRE_TLS: ENC[AES256_GCM,data:uqRyMAI=,iv:CCjOl81aKqOFAOZjqeQscsI2g0bfIER9kQQ4o77ZraU=,tag:gkzvq3Cw0ZoeHes7xr+7bA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT0xlaWtRL3ZHVHRGTytU
        TFB2RVVtT2V4OTVJMkxLeUt4dlVkcHVYc2pjCmhkRGV0TFJWWFF6RGtDTlJjM3Ax
        amdTTWNVakI5OE9yblErdGF2eFMvaDQKLS0tIGtNNXYvcGZERUx0RWU0YkhyTXRu
        dFRnaHROaU4wKzBXVDhZNmh5VjYyVHMKR5X3zKHbkW+ZwxVZQjABDAbWOoZT1whu
        3eofMbVn3li87SPzbn4vA12MzVK+OEhvEACLe876LUCfYe9xctyXOQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGsrdVhQSmZa
        c2ZrK2FvY0ZZM2dhKzJwMlZQOHFHRjlCWHZDYkp6Q0x3Z3YrclJkdG9RUHFUUzhF
        UzkrRStQd1JwaTBMUW5EMEVuTnI4Z3lld05GUkdDenlXV0RUSDBHMDJrUHhjSHdj
        bktXbDY3TXZ5NUhNWWNEZEFzM3c5d2lUSmUwa2lqRmtOVzllcTR6Y2VWZ1M3RUZn
        LzZudDdTWnBqSGVIbC9TbTFxdTRZN3hGSXNhMG5TMHgxNDhoaUdTYzVlbmY3UFVs
        Ujd0Nmc0M0lwdU14R2hRU2YyWmNsdWgzYllYMWlMMmltNG4zeUdFOFBKWkFKM1Uv
        cC9qRmVyWlg3aXNwMlc0SkQyWHNCak50Y0FlNnV2WFptSGtWNVlpQ0xTc1ZRekZp
        N2UrZVN1aXRpLytZTklVTkhXdkM1OVpxaDBSajdEMXJuQytCVzBYTHYxRkR2RVd4
        aXBOWFlsL09SN3hPRFhrdXBnVXUrTmRCc09zaW02SUQrNUNjSlplUWxpZ0RkVml4
        RW52eUVEL1VUTmJYL2M3MUg1bUwySmRVZ3AyU2FyNWd3ZG0zbzI2RVZINGNjT3h6
        WXEvTzRkZnl4MFNQRlF2SThtNmR3K0xlKzMyaVR3VHorUjQ3REYxR2JTbGFiMFEr
        amJXQW9pZW1SVWdFQlRZZW0yMmVEclp4QzdLcnVqdGEvVUhkdzEycWZQUzIvQnRo
        OUNqMmJveXhVQ1JoV2YxTDBHYWdOczJVcUVvQmZpQ2I5b1I3WVRudHJkZXp2ZWlV
        V0Q2cVkzTU0ralRnZElteCtDSkNXTXY5NmhaU0N1ZlJnbURMTDNqN0pYWVRaenFo
        UjRjQWpCT3E1dGpIS2RMK2k4S3hmNzJPSW82TWRHdHZ1d082SFZjT2ZaZ05lWkR3
        UWNmSmNlS2RXOHdjZzRLVm1nOGdzcEQ5VndLd0xTc3ZsRnNUdktzMVVHL2dqeEtR
        TzBDVHVTRjlYaFVjSERHV2llZ3pHNm56R09JWE54U2lEYVVNRFdvVGJaZWpPY1N6
        V2tXZkpvWCtkVzNURUdSVU1nS0RjZGkrZzN4ck5KdktoeHF6NU9DKytWaUJCUzB0
        elQxYjRNMlA0QUJQMUk4Q2lZYXgzOXN1ZEUvbnJkcTdrVFdiOGZ0ODllR21XZGl5
        K0Q2bFFDcVJZalhWRnhoRGE4QmE4RUJjMHhrNWhTQklqWDhlSDVtL3BIa3Awam43
        WHJLOExCY0hOTnBDQ21ybjJEV1JLekxQdzdhMUIrcTRKTU1xWVFCRFJ5T0NYdXF6
        M0gxTEpZeU93K1l2TS8zRW9WQVJrRWtIUGZPOTF1UTl6QUg3UWEyRzlRZGpkTkt1
        c25NQ3RsUlRrQVpZdkwxUXhBNEY0eEdGM3BGZkNkTTRqa0ZJakVHcytJTFMrT2U0
        RkpBVDdBUXVBR0plTTZXajJ0cm0vMXNiVENtMGxaSHlSR1VYS2xSUVh5NmZiRG9a
        b2JaazVXOElEVXJlb2ZSSkVTTDZqQTRDMTlZT24xb1I0bWgyaTlBeC9jTUMyWXJm
        ZkE3SDRMNFFleWdpZFhPWFcrSys1WkdXYW04ekQxTGlPSGwreC91cnFhbXJ1d2Yz
        a3JCVENQT2dZbTU4RDhtMXlXRC9xUHJ4am5senVuY3V1UnN5cTFsQTlBbS8vZ1pG
        MDBRaFc4ZTFoZzNIeWJHdW45L0sraTZKa29hbkNqdHJCWU9OVS81bVZYR2kvWTd3
        azB3MmNKaUVzamJDdmpIWGdKbXBIeGJnSWkyQ2RPelFlbEhBbW5YQlBPWTJxRTdn
        OTJNK09SR3grbnV5N0ZrMExBMi9xYWJMVXJ3aUhiUElHRUppeWRCTVF4RXJNRTkv
        bTlxd1JkYW5OTE52T2xYS09lcExELzhaWVZPblVSMzdEVUlUN25OMlUyaWtoNFp4
        Q1hQS1Q5a0tESTdreHh3ZGNQMEMyMys3clliNGoxbFhmOHVQZC9sNkUrTGhGdwpE
        bXRvcnE1c0JyNEdNclNrVFVwQzdkMEZNeFJSSm9ZbkZPRjZmdkV5Ym5rCi0tLSBx
        TlFjYlVLRXdUdGpsdnJmWXJjZFBjMjNCTzJ5Sm1aTXNOZzluRkdZT25RCrWgzs+n
        SSy6r989Y6jOB5WH9R+oC+afvXmBkmMufdypa/wYg53WI1gd0IDXzZ3EfUcTcupp
        W926LzzDQX/1uEY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-02-01T13:14:14Z"
  mac: ENC[AES256_GCM,data:9mTao/GMzeY1+rZB7KLaNUGb7NI0sj9MqyNrca5KXqTWCQbxr4TVFHr2kUOa/88exSCJDihRarV+27nUyo2EYbj2xtdzPeXveDgxObRjdEGYE99VvwBnPMUqEehHz5+5YNu5GzH9RiWJTfxxH6qhQUH2Zu7weOjiccXXBARHtTE=,iv:LsDdK75LY2PCbVJlzSqoW4VO/erOUNfztkaYSM/5IxU=,tag:DP0vdWWxBB0gKq/AnJhEFA==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
