apiVersion: v1
kind: Secret
metadata:
    name: infisical-secrets
    namespace: infisical
type: Opaque
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:PUx57VOgOxcsVebyLTUrFTKRHL+7BHlkQInRm9opSQbjnxRbIIFIM4xrgAs=,iv:D0vqz8Wpy04oJpgvlbcr6GfxW4Rn9eDqJHis8T85dpE=,tag:eGkcSSPXKHE8VlMLL7tkXg==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:WuIXRMxME2EuWDVnC6tmKg1++bOc0Nf3LHU6b+1/+AU=,iv:Le8oUYV6JPbms3M4J3wdBni+DzRl0LQ6gnxQre1O+fE=,tag:YDU34BBdEuBpgHHLc/BmIA==,type:str]
    SITE_URL: ENC[AES256_GCM,data:IvXXJTRmGFNAv3T4iBsif4HDZ5WiO/upcsSOKrg1N373xQ==,iv:ETgJcwPW88uRAsfaQez6He8RCW1Ns8Y3lbFTImujk9c=,tag:08X3fHJgkj6vBx0Zk6Nm+g==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:Ad/yQvgqtL3FI0hUXMccNfOZOPh5oCriSxS0+OEHO4Oevy7SiQsCb91O8k9knrL/4nLt,iv:ccd3ogozBJW+pGfIZYCbtFPO7+XyN645G/VepxAKrok=,tag:rB0bvKfbFTqhCdFFoTUx5w==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:EtpyECPbR+jzD/JTu/suOZ2amVvTEZgvBHi1Spb2Kubp,iv:Uij5jcri4uGJWqyzRgqrnIc4IxVeCaEuhyAc5puw6xk=,tag:R7O4ekZYwI51HGh0t9JGeg==,type:str]
    SMTP_FROM_ADDRESS: ENC[AES256_GCM,data:2wTjcEeeUeTUlxsyAU4TfwDSnzdqQXk=,iv:WfAUsJKOqjuJ5hqlH4ixv5DR8/bzO+QeLKopOk9WEpM=,tag:OHpynG2RN5/yzdOFlH+Z7g==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:KGbcnMsr6Dsd,iv:5RwS1JgFIy5V2fh+OY6rm+G1wcH3L7BuFTx/z6GX6aU=,tag:lyzV4UucasUFwVWTIQWgWQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:drBIZA==,iv:j+D4GjSiubYcJpFbDDYAs7I2OfVSk2O1z+VYzIisl9w=,tag:bsflF24iJ7j5cpTyB3MKhQ==,type:str]
    SMTP_IGNORE_TLS: ENC[AES256_GCM,data:rOioRw==,iv:riWmPffiUxKurBmWdaRw79VGvpIJ/VVDvxvj3XfNM/Q=,tag:7GGn4DC0ir+4GtPWGEb1mw==,type:str]
    SMTP_REQUIRE_TLS: ENC[AES256_GCM,data:uqRyMAI=,iv:CCjOl81aKqOFAOZjqeQscsI2g0bfIER9kQQ4o77ZraU=,tag:gkzvq3Cw0ZoeHes7xr+7bA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFRoRms5RjBz
            NDdBeko5ZU9FTVFubGtDT3JCZU14anVKQjF5MEFKdzBFaFQzMzlDZUN2Q1dwcVhL
            ZHk3SUYyR2dxeHVBR3IzTzFOWkQzK2lQSFdGVWl0ZERSWDZBYVFzTGM0bkM5TVFp
            eGE4Y0NWa1NFaXNoUjdWMWRmSjZYSWk3N09nNWNsYk9RNjZRY1pwdnh5dURQU1FG
            NVQxaFJnNmJVSnBlMEFoVEdzN1QzWUlWanhzUFUwRWVxcXc0UlVQSjRlYm5XcXQ2
            ZVczek1HU29teEhubU43Y0Q1ODFPS2xDTEZKU2hYa3BtWDFMTjl0SUsyaGloNHBG
            WEV5d29qSVJBSWRsUitTdldReUgrSk4zSU5qeUpHTkxhRXhCR0lUSEJoc0dUN0Rs
            bzZIcldKdk5IRm1qNDRkVktHbndDWDVLdXpJbEp2dzVhd3JPaXJUdjN0UStoS2pL
            MFgzZ3JkSWlqS0xxUkU3WW05eDlPV25uNjJudm1xSnhmOGFWZkZKcjczRW8xRHV5
            ZEJ0NURnWlErMnNaMUFqYXdSR01Ld2RRZHRDdk9TT09yaWZra3pLMUtPM3kxUEMv
            MDZjT2hFM29nbHl5VzdXSDFhL2xhWkxQSkRnaW1hckdreklvWGE1RXRoQTdHUTEy
            WGJFSGdxVlZobWhZTDkwSXJEWEQ3d0F1clV1bW5icGRrdVpla3E1OUpRWnlrOC82
            VjVzdDdFNGw2L1dKYkNPdzRNODJncTh3eDlZRGdkL1JnNlJIdERvUzFPMVpRM0tp
            ckYvSzBSVml6dVBjdGpXUm1WNXRmMEI2VGkrZTRROENpMUcwMDRGbjUraHF1Sll4
            d2VJUlgrUkFkWTZ6VVFQRTQ3TkhyTVdod3M2QXA0L1JoU0Y5SEZ3YTBVTFVYc3Jo
            N0QreEpYOVdMVGlYVHh3K25DNWRyeVlBQ1U0N1lPZzlYa2Z2TFFYQlcxdjNxOE9a
            YW4xcXJ2Y2hHR3lxVU1BUHMwUGRPK29JVFdwNVl5Q0UwandINkE1bDVBRU1ZKzJB
            QjVqakM3VmxVVkpNWWtZY001TlFoNE5kb0hmSzgyb2dBZkhiMlhLMTVJQkdORHpz
            NVltY0JVR2t5MVZnQnBnUko5OGt5U3dENUx6czBNNWpWR05vLzlvNWpOUVlWVStu
            V05GSndMTnRDeFhGV0xEQXpPWjVYcW1vcTdIMEg0MGhIczg5MnVTT2FLdXZ6VTV4
            azBqSFpYZHBDNjdQdDB2bkhLRXVSaTdENExMNGZVd3FOTDNIODRUdnZyR2ZDQm1E
            ODBWMEdWemY5TjRGSmJzbnFLWm1sSkxoWmZ4OVhOeXJKOFBWYmF5bWJTUWhuNTN5
            Qm1aVDRoOS9CbDB2U2hCbnNKb3J1a2xyeWp1Z3lyMlpKMEtJSDAvUmEzUUhOaFR4
            V3dPaVZDMTBXb3hnR3pMRXVLWDJtNlgybzVvY2E2NmoyUklWS2VHeW13OHd6cWZ2
            Z2Nvc2d4Y2k0ekdTYUVEMzN4SVFJSzF4UW1RS0tDYWw3eUdlUnFuQnlyekxOZEU1
            T3c4NmVUU2Q2SDRUUTBHT3BTTUxZZm5JWktoeXNmUHNCb2ltVVZzQmw1YVc4TXhq
            VWRtQmxUY29GUnBqeTk5b3dLNWo4Rlh2czBWdTMzSGdiZHp5M0xrRWp6dkFuVjhI
            OWFvbkpiWEVlTzRDbmhvdmNOOXUzQ2NZYlhPaHQ5bFdsekZlYUlnTktYWUhOTUc3
            ZG5CN2dGeFRaVHVxS0pNWnh4aFFSK3E5V2g5b1BzN0c4ZUc3ZlNDTFhndTBEOGZw
            Y0N2RzFyWDQrcSt6c2FINHZPYnVVaDFEQjdyZjFUaU51R0Z6MFJlZUJrRElEQU9V
            b0RBTFhZcDZDSDNQaU55eXNVSENMSjU3aFI4cVpEWkd1bytQU3dhUndsYTEvYnNV
            YXBUaHBCN2E3aldSZDNYeHhsZXhXeEt6cEZWZjZXSnBabXVZSnhNR25nbzNNdwpF
            MVUreVVIbWJocFp5akZlR0VmeDFvNThYTVZyZHRhdGNYTXdMTERXY0NvCi0tLSBk
            QnVnM1JTMTJsZFg5cjRYTVJETEdhSFNmTzBXaTBpYUlFVjZVR3MzUklBCiYGhVBy
            2MCrQAKBfIx0qiOXzN/VUnIqlT0EGqdnelspy5/KUPSQrC/6nKfVdYRXZIODcUfO
            4u6QrK3xKJfJigk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T17:07:26Z"
    mac: ENC[AES256_GCM,data:mzUuSC1AtVoyMDJ6KI2vDsbFLc1eeVzDfkk4lz9wor4pRiCNqbRHK6RYavAP3wN7yLPhpn3NVd28Jw1bLt3BFeWZtTgPd5wJg/EYF9uoQVzAcx5ttT3jLERe1kLOlCLYakT7HBNAOLpp6b+jozSXgDAliqMwvwvwu1g9yNweP3g=,iv:Upt9Ih4JstXuyaHAg6lL8C1o3DN1wI/AXqXe5xI+EdM=,tag:fXhnFM1iLGzjhMJa/baJ0g==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
