---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./litellmproxy.yaml
  - ./litellmmcpservers.yaml
  - ./models/
  - ./externalsecret.yaml
  - ./mcp-talos-serviceaccount.yaml
  - ./serviceMonitor.yaml
