---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmproxy_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMProxy
metadata:
  name: litellm
spec:
  # renovate: datasource=docker depName=ghcr.io/berriai/litellm
  env:
    - name: LITELLM_LOG
      value: INFO
    - name: LITELLM_MODE
      value: PRODUCTION
    - name: REDIS_HOST
      value: dragonfly.database.svc.cluster.local
    - name: REDIS_PORT
      value: "6379"
    - name: LITELLM_MASTER_KEY
      valueFrom:
        secretKeyRef:
          key: LITELLM_MASTER_KEY
          name: litellm
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          key: uri
          name: "litellm-postgres"
  generalSettings:
    health_check_endpoint: /v1/health
  image: ghcr.io/berriai/litellm:v1.99.0@sha256:570a872d2fde8f1bc4a147634810941103c14697270f0f2918c5aa7d8201cac5
  litellmSettings:
    cache: true
    cache_params:
      host: os.environ/REDIS_HOST
      port: os.environ/REDIS_PORT
      type: redis
    drop_params: true
    merge_reasoning_content_in_choices: true
    prometheus_adapter: true
    success_callback:
      - prometheus
  replicas: 1
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 256Mi
  route:
    hostnames:
      - litellm.${SECRET_DOMAIN}
    parentRefs:
      - name: envoy-internal
        namespace: network
  routerSettings:
    num_retries: 3
    redis_host: os.environ/REDIS_HOST
    redis_port: os.environ/REDIS_PORT
    routing_strategy: simple-shuffle
    timeout: 600
  service:
    port: 4000
    type: ClusterIP
