---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: talos-mcp
spec:
  alias: talos_mcp
  workload:
    # renovate: datasource=docker depName=registry.erwanleboucher.dev/eleboucher/talos-mcp
    env:
      - name: TALOS_MCP_TRANSPORT
        value: http
      - name: TALOS_MCP_HTTP_ADDR
        value: ":8080"
      - name: TALOS_MCP_LOG_LEVEL
        value: debug
    image: registry.erwanleboucher.dev/eleboucher/talos-mcp:0.0.2@sha256:ad1b388e20cbe171763ba0ff85ed32856f2573c9c40f5081a83c96b3b57f0d35
    port: 8080
    volumeMounts:
      - mountPath: /var/run/secrets/talos.dev
        name: talosconfig
        readOnly: true
    volumes:
      - name: talosconfig
        secret:
          defaultMode: 0444
          secretName: talos-mcp-talosconfig
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: victoria-logs
spec:
  alias: victoria_logs
  workload:
    env:
      - name: MCP_SERVER_MODE
        value: http
      - name: MCP_LISTEN_ADDR
        value: :8081
      - name: MCP_LOG_FORMAT
        value: json
      - name: MCP_LOG_LEVEL
        value: info
      - name: VL_INSTANCE_ENTRYPOINT
        value: http://vlsingle-vl.observability.svc.cluster.local:9428
    image: ghcr.io/victoriametrics/mcp-victorialogs:latest@sha256:753bb4fbe402ca1a782842f44636830f9895736f11d7fe783b924f8a0daf083d
    port: 8081
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: sidero
spec:
  alias: sidero
  transport: http
  url: https://docs.siderolabs.com/mcp
