---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &app litellm
  labels: &labels
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
spec:
  endpoints:
    - bearerTokenSecret:
        key: LITELLM_MASTER_KEY
        name: litellm
      interval: 30s
      path: /metrics
      port: http
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - ai
  selector:
    matchLabels:
      !!merge <<: *labels
  targetLabels:
    - app.kubernetes.io/instance
    - app.kubernetes.io/name
