---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dashbrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: dashbrr
    template:
      data:
        PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        SEERR_API_KEY: "{{ .SEERR_API_KEY }}"
  dataFrom:
    - find:
        path: /arr
