---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dashbrr
spec:
  chartRef:
    kind: OCIRepository
    name: dashbrr
  interval: 30m
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      dashbrr:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          automountServiceAccountToken: true
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        initContainers:
          discover:
            image: &image
              repository: ghcr.io/autobrr/dashbrr
              tag: v0.6.0@sha256:55289a0487008f13388e4541fc95079f3d3a9cd660dfba170861dd4b6f0b7292
            args: ["config", "discover", "-k", "-y"]
            env:
              DASHBRR__DB_TYPE: "sqlite"
              DASHBRR__LOG_LEVEL: trace
            envFrom:
              - secretRef:
                  name: *app
            resources: &rs
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext: &ctx
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
            workingDir: /config
        containers:
          app:
            image: *image
            env:
              DASHBRR__LOG_LEVEL: trace
              TZ: ${TZ}
            envFrom:
              - secretRef:
                  name: *app
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources: *rs
            securityContext: *ctx
            workingDir: /config
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /config
            subPath: config
          - path: /data
            subPath: data
      tmp:
        type: emptyDir
    rbac:
      bindings:
        dashbrr-discovery:
          roleRef:
            identifier: dashbrr-discovery
          subjects:
            - identifier: *app
          type: ClusterRoleBinding
      roles:
        dashbrr-discovery:
          rules:
            - apiGroups: [""]
              resources: ["services"]
              verbs: ["get", "list", "watch"]
          type: ClusterRole
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8080
