---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dashbrr
spec:
  chartRef:
    kind: OCIRepository
    name: dashbrr
  interval: 30m
  values:
    controllers:
      dashbrr:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          automountServiceAccountToken: true
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          discover:
            image: &image
              repository: ghcr.io/autobrr/dashbrr
              tag: v0.5.1@sha256:7d138a4977c29b0b28692a4826a5ce3b41fb0b4c17454d146a900f8b05d48522
            workingDir: /tmp
            args: ["config", "discover", "-k", "-y"]
            env:
              DASHBRR__DB_TYPE: "sqlite"
              DASHBRR__LOG_LEVEL: DEBUG
              DASHBRR__DB_PATH: "/tmp/data/dashbrr.db"
              DASHBRR__CONFIG_PATH: /tmp/data/config.toml
            envFrom:
              - secretRef:
                  name: *app
            resources: &rs
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext: &ctx
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        containers:
          app:
            workingDir: /tmp
            image: *image
            env:
              TZ: ${TZ}
              DASHBRR__LOG_LEVEL: DEBUG
              DASHBRR__DB_PATH: "/tmp/data/dashbrr.db"
              DASHBRR__CONFIG_PATH: /tmp/data/config.toml
            envFrom:
              - secretRef:
                  name: *app
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources: *rs
            securityContext: *ctx
    defaultPodOptions:
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    rbac:
      roles:
        dashbrr-discovery:
          type: ClusterRole
          rules:
            - apiGroups: [""]
              resources: ["services"]
              verbs: ["get", "list", "watch"]
      bindings:
        dashbrr-discovery:
          type: ClusterRoleBinding
          roleRef:
            identifier: dashbrr-discovery
          subjects:
            - identifier: *app
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: dashbrr
        globalMounts:
          - path: /tmp/data
      tmp:
        type: emptyDir
