---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: llmkube
spec:
  chartRef:
    kind: OCIRepository
    name: llmkube
  interval: 30m
  values:
    controllerManager:
      leaderElection:
        enabled: false
      podSecurityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      replicaCount: 1
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 80Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
    crds:
      install: true
      keep: true
    metrics:
      enabled: true
    modelCache:
      accessMode: ReadWriteOnce
      enabled: true
      size: 100Gi
      storageClass: miroir-replicated
    namespace: ai
    prometheus:
      inferencePodMonitor:
        enabled: true
        interval: 30s
      prometheusRule:
        enabled: false
      serviceMonitor:
        enabled: true
        interval: 30s
