apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:XxLEUtn6iI0vVfTZ34mAEQs9brkpJ8lbJhS079DdYl4=,iv:cwsQcfKeyo6/xsGC5Yf2tTHO/QkUR4KLSDgKBKbV+8U=,tag:DkCjpS7mWxtnW5vZ7A416Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiL0NqZFY4YWJkVE5jVDFU
        RlE3Nk0wQ01NSjZ6UFViQkR0QWcyU2orOVhJCk56Um5BME5jQk9tNFZpcHFpUVNk
        cDB1Y2ZhbndteFFwaE91aWZ1YngwQ2cKLS0tIGtsNGNqUE83T3lJUytoWktwRmZS
        VDdLNEtLN1N4TnNsVFhmZDJtUERzWUEKSTDht+7RFFmjy+Hzs1ZViCspVukTTOpc
        fPPul7vmxTnKalsTM8YC3T4yToZpaPpNzNPQ/dQAlCnvM84G7vHmUw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFg3Y01xandz
        Z0J0c3NNL1N4czJIb2NJbGdPa2dCNFNUZmo0QmthWGxuSkJEQlExWklnRkw1TDdG
        OG9qc3dNNTdZTkhTSDF1MENNRU0waVp3b2VlWUY1K2NYV3ZSSWRyUVJhcU9YSy9P
        VUFLeXYzU2lId09kVHZoVWIya3Z5TEdqOGpPRjNzTVNDRm1lek1UZDZOb1B4aUpq
        WGxTL01GL3Vxb2cwd3VqZzZjQ2JLQlZwWWxzYVZBMzhCbVRydWowTFNXNWtkV3My
        Umd0TE44TmZCeDNROTFEUXQ4ait3czcxMDZlRytQZmx0ZnNnU2hmaVQrekdJMHA5
        bkt1YVprSTJ3MlhsM3ZXWDIxNG1HRTZiMHAxakZOQk4yTTNQV2U3MzNSNTlMTlZQ
        cHJtbnd1My9DN0Jpa1lRL1BIK1JEUmM0eDladjU0TktoNzRXTWFPNFVWb3lxc2Rs
        aHJpNG5IRU1ZcEdObTRHeDRyWjB0ek1Nd2s1eU1yMEJVZTh1dHZpbFJLRXE1MkZJ
        YkMrUWZYdVY3ZzEvbDJXclFaWk41TVVMQURpeWxSby83MUpUTXJRYWxKbk1yc1Bo
        QmVhYThZSDlmK0hUUldhVWRITlhUSVpkelhheCs4SEVLWUhha29CT2RuanRvVzhr
        OW8raWZrNk9jZnR4R0hlOTlNSE5xVy9JWlZmT3ZUV2h2SHhlWit3QmJqY3V6clhs
        dlNQSFJlM1ViaklVL3MwRjV5azRDNWlKdkxGalg0VG81RnlCdDZYT3F6K0dIcHZ6
        bU1TN3NQNEhIRkJyMXJ0NzM0TVV5clhOSU9kSlFnWkFPV1I5a3ZtUys1RUJHZ2tJ
        VFFlMkRFdDJ2N2d6YU9DcVY4NkRxNkJiV0FTU2NSalhRTHdweXJWWVI5ejhtdTJi
        eDdYbEdMV3UzMXcxU2k4UHg4Y1lsOTlRZWh0bnJvRzBIOGVyR2gvTCtGT2xLWVp2
        K1hXc3Fob3p5S0hPZEx5RFRjbFl4WklvVThlQWgrVVFsNW9PVDU3bFRkU3JKbXNv
        R1pTcWhteW5iK2xlRlJaaXdzYXMvQVRqQmR1d3ZoNjVSc0REZkdzV25EZm9CNVVr
        eEJ0MFdiUHZJZW5vL3EwZWxmeHE2NDBySkdzalNpZXJmek1HSGxwZFppckpFQ2lk
        dDluUjFpVUxuWUU5VE9tTzZ5bGpzNFBNcHFPY1JQVEpCV1FVMDB3ZG9ML1M5RUF6
        N05vS2hLQ1JoekxiVnhZOUY5T01JSVhGVlZaR0ZOTnVZcmNabDhPcDhxVmtxakZx
        Z1NzQWFPQmIzakJQVktzc2hvL0s4RjNCcmRvNG1UanRMai9BZlZTN0JodG9SV1Vu
        aXRLcGJibEJSNzQ0V1d0UHdoeHFvMHdKd3l5OUc4Zk14U0hVenBjbmZpWGdQRVhV
        NTBkTGtrTWt1eWpQbkV4em1CcWFPcmRzaXJVMFFaWTFReUlxL3BNSUlreldBM2cy
        Z0x6dHYxNGE2UlVqWFBZTERTTm1IRmxjY2xKbVVMWll6NjZrZ1J0c3dGUCsvYkg3
        NDNuUDVlM3h4Z0lmZkNQSE5SeVNOMUZzUW5WeW9zejMvWTFZVHlGL2ZCRFYyVHVN
        bmZWL0VhYmJtdE40dGJ6RGEvVFJWVDdSeS9JRUtEZ0tZKzgwNEZNMCs0em5hTVVE
        cWxvVmxDdTRFWWswUERObVU1Y2NjYmZtZ0QvV3lHcEMwY1BETTJqNGZnT0xwQ3J4
        YjZNM3Qrc3NGWkpnL2d6Ni9GdW9VNTl2aXYxd3pTZGFDNkgzU09nZ2FjQXFObTVP
        QllsWUpPaStxbEVrUE0rSzQ5RlNxcDJFd0lQa0xWZkpFNVErUW4wUUZoUElsSklj
        VjVXV3daME0zVmpYSmdLYlI0NmpNRnZPdW1rNStQdnplSlpWWTBhRUl0dCsxRS9C
        M0pNVEIzd09obGxuYnVRcE1hVnV5TVM0emJwRE1OU0c0WWZYOTJEZUw4M0tEUQpW
        SEs0Q2JZazFjSHh3ZTIrV0FJMVJ1VHlzM0NmbWtlcFc1NWYzeWVvVXN3Ci0tLSA4
        Y0xhR0VCSk16VGNMM1daWDBJSjdxMHJpQzZUdXUzbTlIVEltRnVKcnVBCvjdcmXq
        BYCcIf25URaCNg+FOlACiHAz8BHnjbhqh+Soub87JKkhgyJ03pESJEMapUXkLt9c
        uD0CHOYXMZvlnN8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-14T17:30:51Z"
  mac: ENC[AES256_GCM,data:Co2e0PtVMx1ljD6tlG3fgbe/XgWfH31cvs1Jh6VkKR+PpkbkCMDZMN+DoWeoAcmMO3bd4aZs1mmOj5Au+SWj+EYq7kVlyh9cSt1afAPULm5jOeEW+LLLFl5HEikNi3WfNw2QYHXvTYmx++d16cxfbtrX2VtoUuG6TkgiFUA7iSI=,iv:Kj+SSNAkbytQoR65xPmnJu2AmfqWXilAIQWp2YcJMao=,tag:1Z/adi9MNxUO++KerjeKrg==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
