apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:XxLEUtn6iI0vVfTZ34mAEQs9brkpJ8lbJhS079DdYl4=,iv:cwsQcfKeyo6/xsGC5Yf2tTHO/QkUR4KLSDgKBKbV+8U=,tag:DkCjpS7mWxtnW5vZ7A416Q==,type:str]
sops:
    age:
        - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV0lWelJTK3h3cUUyVnVR
            NjFKTUY4RmdkajFGOHdzdVFGNkNkR1llaWpJCnAzMEpoN2ZtR3J3TmR0ZlZTazR0
            d2FkZGpvajN0OGhjMS9tZkU4aTUrcDAKLS0tIG9nbm1OT2MxMXpmOGZuckpPU1ZK
            aFJ2c0hxTkxBQmM3enZrUEFlQng3aDAKuAk2yfJi4045YXA3CrLXOuBT/qMLuu5D
            lqfp6QattCNcs484+yB2GzWKZbNst1myVIfZUoZI0oBxlHiSyfM4Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T17:30:51Z"
    mac: ENC[AES256_GCM,data:Co2e0PtVMx1ljD6tlG3fgbe/XgWfH31cvs1Jh6VkKR+PpkbkCMDZMN+DoWeoAcmMO3bd4aZs1mmOj5Au+SWj+EYq7kVlyh9cSt1afAPULm5jOeEW+LLLFl5HEikNi3WfNw2QYHXvTYmx++d16cxfbtrX2VtoUuG6TkgiFUA7iSI=,iv:Kj+SSNAkbytQoR65xPmnJu2AmfqWXilAIQWp2YcJMao=,tag:1Z/adi9MNxUO++KerjeKrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
