apiVersion: v1
kind: Secret
metadata:
  name: discord-flux-secret
stringData:
  address: ENC[AES256_GCM,data:4Vm+S7Lke6OVbHyPBNit7wHAuxXet0oLvFwLHXJPyztZgqqm6rIkBU9qw6AlOFkahtYr+SIK923X19SF88hdWDUFmus6xrxQDvibnzxyxhga280PgoFIgzAUKYPWgEPtIzLvS9Bzk5ipd7f+d5b5/h/7l89Ky0I/8g==,iv:OC37j56JBaNkJvNISuDYK+BaC4QhSwPB5FoOUjzt/8Y=,tag:sEliQKdcj8EWpcggRoIryw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDVCWlRTK2FC
        RWQzN0dWQWJ4VlpqYlBtWExidThXUjZRVjNuN0J4WG13dnd2cGxHbCtZNlI5OVp4
        Sk1TVXZGVDZJcHZGQ0NaQWM1YnYvZFdqc3BxSWNsSUxOeUl1YlhjbGRNbjFBRkRB
        Y0lYd0diNXBZUTZJaG93UlVSSU91dWwrQVNmRFdacitTMFE2YlJDLzRkMk80L3FZ
        MGpBMkJqNTRQMkxYby9md0h6dDkrQmllNGQyckN0Vk10UGhsRmQ2c1ZXN1BUQitk
        TXhDMVgwYVo2RFN0VXg2ajcwTlUvMVZsUURTaVU2ZnkrOEt6YnhjcXVHUktRek4x
        akQyZ1oyVWRFS3RMZjl4OFNtNHFmb0xWWkthVW0yVlZrZjdzTmdiY2pzMmY5OXVo
        YVI5Y1FXUFFVaXh3c3lnKzlWVWNZYW0rN3F3Y0xTWDhhOW4zMnNEVUhUZzdZREtU
        V0NFL2lOelpKaWRYVmpPNEZ3dGJOd0RSOUdTM3JvU1FrY0tBcXJMUnVFY1pqT2x3
        WlhPdjgwYmN4OGloUS9tQVVLUFdJVGxreWFlY1JGSlkvaUtqYUJvdWFuMWxWVVls
        blJEN3BWYUxjSlR3dFNUQmM1cnFFYmFERk45QTg4Y1pwNGkxV3doMGFoWjk3OFcx
        VWhIMWh6bjlyQitzd3UzWU56TFR4MlBDMnF4elJ5SkpKTUd3VFY5UWZPUVkzMzl4
        elFPcW1XT2RPYlJWbnZTSGhiWTIxRTdyaEMyNUQyU21sU0tEdE5KUnJHWUhZRzd6
        OUtlM1JpTytGNWx3NlJvNkd6dmdEV25yMmRobkhmZGlHSW9sTWN2THk3cWp3c3dE
        Qmhwd2IwMFdrYmhCVGQ2Z1VQKzdxM3VGMXlSdi8zZGhJRHlCZFBQOExEZHpCSE5Z
        cHBWUTNKQ1MvcHBRVTdrelNqbFlGY0srQlBybEdVZzJZVlFQMU1LZ3BLM29zZ2hE
        YlRlWGtXdVJ5QUluL25pUTFBVUNCQU1XaFczZzhnYksvR3QvV0JqVzZtRXdmK2dv
        MklXT2dlSzVKdksycXpYSFdNSDFXanJSOTFKVWlzQ044L2sydXhXenpaaTVNcWp3
        NDNpVjBvK09heWlQcW52NDdkclJ2Rzh2VVljaWVSRGN5Vmo0WTllNmlOZ0d5Yy94
        Zlc4aTQ2cnNoQzNtd1BoUUJaUUZRMnl5T1pmblZETG1HNEJ2ajREQXorcDBvMkMr
        NW44ODdiamV4ZktJbnlMRVhKYnA5bXc1RmVqc2VkOXU4SmZnNS9aUEp2RzNTMTd4
        cEdRQ0lac3Fwa3BidU9kdm9FLzgvWU5yV3lBT1NFcFYxVTEvVTZ2SDhia2R6WDly
        bDBDMTFlSFNaYVlUVVpoVUJhWTNhNnREU3BUR2Fqb2dVcTc4SzJPSmpnSkQxM1Mx
        N2F5WjY1a29SQjNuUkhFZkdzcmJmOHUwYmwzRzI4NjVnRWRIVUJMMHVncEVpdkNI
        clNtNVBJUlZnbjdqQWYxNWdXNW5RUWcxR2pzQjJJU2tHWWhZZzlNWVRuelI0dnl1
        UjFobFBaVkt0N1IyMDBKemFhckhQeUk5b2UzRHRudndzbWd2K1VOc1BUay9IL01I
        MEhPcDZ2U1Y1NVIvZVZKRU5OR042TmNTU2Z1eGtLaUJ2YXZUMkxDeGlRN1RDS25n
        R1JPRmpzb05xc1JUUXdnRE0vMDEvZW1CRFhkWVFETWlraEhtbithN3pDRkZudGJG
        eVNiUE9scmF6NlpJcVVlcldvclZBa1haelM0WXZ4dG9vQ3hibkp0ck9BVStucnZn
        blRqVUV0MEp0b2QydDNYNEoyV1RnWDFHQ2pYY1FhTW80Z0FzRFV0dTQvTzRmNTRP
        QkZKMXVxUGhLL3hzK0N1bkUyMEdpUlFqN09lSWVTNnZSVHFvcWZGUExndGRGaEhT
        dVlaRmVpYlhSbmpGZ3Fna25tSUFCMWJQTDM4ME56b0hqS0tSNGF0YmFURGplQQpO
        elhFay8vZk9iRGt4QStvdEowNFpFK250bFhsU0pEbzU3UUU1ZzFOMmxVCi0tLSBF
        dXEwblJaQkJDSUsxc21LM3Yya05aMGVHTWVwbktrdmgyVk83UTArYTY4ChJugCJO
        C7NQehM91NAqpvUOxbyJ7G3EYzTqDepVcwTIFTUMzGAU/9q1mTuZBQPeFteNvBcB
        6/FSkuUTpqLS8zM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-02-01T13:47:12Z"
  mac: ENC[AES256_GCM,data:M4k3Bouo9SCL1M0skVtMuIAJU5ZOuca+uN+I00pwczyzVx77zmfd/WmhHFF8nT4WhbX/VAmfZTgtaDh8FbfO+GtE8SMWrN4FkSFVVHEkG1W/SVwdqz4sKmHTEfeQ23uZZIGeAL2u8OfSjO9hi0DerWncobbi7qK2bH+3HePk6i4=,iv:uKEZrqM8Qt8NiKwzJ7As8pBamBibA6YrMN05nCaz9ig=,tag:3+K0A/BA0SGhQxSRyKHCDA==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
