apiVersion: v1
kind: Secret
metadata:
  name: discord-flux-secret
stringData:
  address: ENC[AES256_GCM,data:4Vm+S7Lke6OVbHyPBNit7wHAuxXet0oLvFwLHXJPyztZgqqm6rIkBU9qw6AlOFkahtYr+SIK923X19SF88hdWDUFmus6xrxQDvibnzxyxhga280PgoFIgzAUKYPWgEPtIzLvS9Bzk5ipd7f+d5b5/h/7l89Ky0I/8g==,iv:OC37j56JBaNkJvNISuDYK+BaC4QhSwPB5FoOUjzt/8Y=,tag:sEliQKdcj8EWpcggRoIryw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdG05Z0dSWElPc2RCQ21z
        WHgzSXlnYUpEWUVFNitrYjNRT2x2TUFDdld3CmFaYlpQQ2V2emJXbDZvaUp6cEtn
        RUhEWTRXYW5pOWljak9RRHlhais5cTAKLS0tIDB4MmgwMzVVTHlCR3JQbXJTWDNa
        R1BPRElkSEs1T0pEUnlreEx0aU9KYW8Kjjc57jYjI3+vct3LihMF6L1aqh8xV0nU
        Iwch2uH2IusO8UyqeSWfMU/UDcv3SPHWR6UkHJ8zuy6sLdnAaTHc7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5ICtNVzFqaHFq
        QnVNSEVlTHQxMWJ6UTFRZERCWHFzb2ZRRjZnZHNiUUNvZWVQcnFTZ1JOUytJUTJY
        ODBreFlWbm90SW1mUlpZWjZVS3g4OEVwTUhkNEZWWFdWK0wyNTk2TnRtNWpjRnRw
        RzZ4dzZQYmJHdW5NNFR2Kzk5ZDM5Vkh5M0JPT01sMjluQXZGQ3BIaWZiUWo3b3RN
        UU5FdGVCZjN2VzAvVkIrN0c4Mm5IZVZYM2JzbDFqc21XTmk4aU5zOGRSVjRlVlJ0
        RGhsZjY0dWt4RVRnMit2MGdTTU5YN0IvaXZlNmVzVGVNZDQ2UU5oRW93SmJhdXkv
        RzRNbmcwU0NCQUJHL3NYV1F1Y3JzWW9aWnJiQi9peGVEeks0Vi9oNUpCanhPVFpD
        MmJCYjZwaitGZTRlbGpRcWkwR1o3Tms2STdmenF6OXhBSWI1dDNjYmh0UGFPTG1r
        Y3ljY2ZwNG1nUEV1ZDlSaFdCdTRscHkvcTNURWh4b3ZlN2dwdEVndzdXdHdSOFFO
        bENQeW4ycmZ4ME1OS2l0L1RYOGZGOGJIRi9pMHhsVjlRWUVHNnFjRkxmWlpVYWJM
        aGh4ZHExakUzTnJjT2QvS3J5NU9pOFdWbm0yeDdGS0ZBcng1UWZtRFFsTGUwOEZy
        WTh4S1d3U3dSMEN0eUk5L3gxKzBmSFpjZlR5RVFzRWtmQXFNRHVuUFJNU2hFVEVq
        Y25KZGxPaC9iQnZ4R2o4MExqY21mSlZjVFA5cm15bjdycFdxZFhEdXhJWm5odk9X
        R3Q4elpYcVNrN1RraUNwcEJGTElaTUxlWmxZMWpwamk3ZlcrRnFKK2Vrdkptd0Jy
        ZzVWWlk2KzUxK2VLSG4xbGxtUWovNm8zbk54VkR4YVZjNW9HNyt5ZXhTaVh2eTBy
        YjVmRndZMytoTGw5NTczOERRZUNvbWN4Y0s4eERwTHVkQURiek5oS2xBd0t0Lysv
        VTdyeFV2eWl5b05zZVVrVDJOdVZ2d2R1aGF4TTBzSEFGNnhRZTIzaXVXUFl6eDJD
        N0RPN21ObitZWE9ndnFFbXNybmFVcUxsK0JpR2J2NkY1UU4rL2tKckxNdWJPVWVO
        eitlYkEzc2htKzJ3REY4eEYwenVmL1Q5aUl2cHk2NzllQjZqMTdMZGlzK3B6YzFw
        WFBoZEExQ0FxMHlVMktIdlViMjZwSngvMEthOFQ3MTJTOUNuU0NZa1Jab2hpL1FP
        MkRlRlh4UFJML3FzV3lxUXVqWlFrTVY4Y2Q3WWdpUTVZOHhPb0hOZWZGVDl4d1V6
        SG54a01rd0xNVjB6eHV0QndxS2h5WWppLzdMd01hODJMcG9mSWlrTG9QdUwzdFdE
        eHYrd2JZdndST29xaEtKdGp0TGc2NnJJUmNDNFhiYWxBaXZLcjJCT0lrV2ZhTDE1
        SHRYL2g0aTIzUDVyTXJ4NnRNTjJxNUVLTUJXdkhVS1FseG11K1JwbzZsUGZvdmRa
        NWpGelEweWJ6VDBTL2hxRXVJemtYaHhlbmVnV3Iva3RLWHoxdzJZaUZZdmFwdlhJ
        NmljL3ZBb1dzS2hpUFRqZW1sQzBiSnJNYWpsMFFGUHk2QWNUbVVBQUVRajFUamJu
        YzlsNTloNTBxZXUzdjlJTG5tNUl6T2pUOGNFbVJhOUZ1R002Rlg0cmlIV0hkcW1D
        VnFvQkx5MWdLc1VNbmZTb0krYTJlNHBjbXludkt3bnM1RXJPQTVOZlBoOVF2UmtU
        M2JyNmt1a3Njb2lrQTFNWGZUMzEwVkZWbURvb1M5RVd3ekowUkU4VTFtL0lhY1d0
        SzRQZDhkVUJxaGlZc3VBRDhKWFJpbXZPT2wzTE4vbXpveWhsUWZMU2NhU3hqOFFF
        SFRKYTd5VHg4NFFvcG5NR1JDd0VTaU9EeEhmMGdPWkh4Rm5reDB1WXRjbUlKaCt2
        NFZ1SnA4YlVyaUJFbWx3QlBETjJoMDVSdHA1ZTlyZjd5VGRjWk1Ra3V2MUxadwoy
        WEc2a2pFZ2ZWOHB5N1B0VkxwaTk4RDNITlpPMnZ5M0Q1TVpoemM2Q2lvCi0tLSAz
        bHFqS2pGYTkxa0I1MlN6ekFVWnh0a0hieXAwdWxVYXJ2SWRuQ3NvS2VBCuqQKZLN
        XBJMZ+wgM8sef8E/pQJwrylAzmJY/TXhb0pvZdz9ohxqFERGchBCIKvh9QDEhwDM
        7JXzUY0edb0xDHs=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-02-01T13:47:12Z"
  mac: ENC[AES256_GCM,data:M4k3Bouo9SCL1M0skVtMuIAJU5ZOuca+uN+I00pwczyzVx77zmfd/WmhHFF8nT4WhbX/VAmfZTgtaDh8FbfO+GtE8SMWrN4FkSFVVHEkG1W/SVwdqz4sKmHTEfeQ23uZZIGeAL2u8OfSjO9hi0DerWncobbi7qK2bH+3HePk6i4=,iv:uKEZrqM8Qt8NiKwzJ7As8pBamBibA6YrMN05nCaz9ig=,tag:3+K0A/BA0SGhQxSRyKHCDA==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
