apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:XxLEUtn6iI0vVfTZ34mAEQs9brkpJ8lbJhS079DdYl4=,iv:cwsQcfKeyo6/xsGC5Yf2tTHO/QkUR4KLSDgKBKbV+8U=,tag:DkCjpS7mWxtnW5vZ7A416Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDBmem0vQ2ZR
        TFBvam9UY2hJc1l4OStkRGlXNmQxTDBtYm5uV0EyZUdQYUtnMHRPV2NKckRZK25C
        NFlUNUNmS1JpLzlMS1N0ZjdaWkQ2bUplMzMvYldhdFlLMjI3VCttbGdRaFhpNEwr
        R2FLNGpNOE8rMXpwcTlGSUNDcS9tREpMQkhDd1lQakdQcncvMFgrV29BTXFYWFlE
        aGhrejRBamhvM29aZWhqZjhoY0g3ck5IVGRrVVJHeldlWjJLckR3QWllVmRrSDBl
        S3FUYlBzcEJxOXpwT1lHTzdFcjFEcDQ5TjIvSnBhZHBDQ0dXb2VHdzU1SnozR0kv
        and6WVVMcmRuNTZsMjM2NG1VbG0xcWlGR3hRU0tRVHhpVHhXZEVFWDExYnNvYjBX
        U1NWNEhjTThGMTkxV2RhMi9zcGhDd0pvZFNPMHUycDBiWXE3RE5yUTNYTHQvT1FX
        eklzQ2lFS21FTDhLcVhGUnNsRHh2QTJ5K2MxNVFsN3ZPSG9ZRDZTOVROMWc1SG5v
        YUI3RjJsTmVVS3BySUtrWEdSaEFYc3l4dWs4S1VvVWFrRG1KbTc0bEtVL2p0bUF2
        OE5XUVJXeVJ0MTc3Y0p3M3VnTFpCQzl6Z0dVbS82bDFGUmdub29aTnRPTTlERFBL
        YWp2SHp5REg3RmZNRjNJYzlmaFFENEhmZHA5S205cjFTbmJ6bk82Y0hHMUdXNWNC
        ZWZkUEdZMDFtWTZBSTN1U2VJQm4xZDh2T2s0WUpkb0lxdDFKbXQyZ1ptVmEyd0tT
        TENocElVdmtmQ0t0OTBlNzQrZjNHNkpUenNqVTFZVWt4RkYrWlA1Ynk5SThSSXpn
        and0RGh2SGhUbk90QjltMWdDM3djdy9IZDdSdDJiRXVJTmg2bHc1aHg3MWNCa1Vw
        VDRGSjJPYnArdkNnWFpvRkIwVDltVFRydGhhTUxVMklRN1h1ZzRqa0lkRERaSUVP
        a1dFN3BuVHRjbWowQVNCak5TOHNmNVZ6QW5sY2RxRFZkUlFNWUp3MVBLbG5kK1d5
        ckRxWnpkQjNUNUpKVnFya2dhZDJZd2hkQkhTUVgxc3d2NDh5SlBDVGtQOCtSajNy
        b01jcHdsVXB0QTg4SElGSm0yVVhpeWpISHlqUU1ZSmJrZ3JUT2JCSUhXelpWZ3ZM
        Rk40ZitoVzJMRHdyQU9tYWV6M3dnTmY4ZDZBUVJ4YlNPUDFBNzdkV1dJMmxhbWlr
        WTVlemZSdEZ6TzVRQi9SVFg5YVZybWh0eFJrQlJmbXRQcEw4TFAyRFA3RzVsQnFQ
        UUpUMmtVdDNabUs3NUxGR1hyR0NUSHI3V1dSc1ZJV2toL2tRc0JGTUFYTnNQdVdO
        ckxZQ1BKdG5lMnBRZVJleTRVMWFOZGVPbjNwS2JKbUVQazNrNVBzdFA4N1pBQ1Zn
        R3VwVURqamt4em1MS0QwazRsRXAzYnRWQm5Od2EvdHRyK3B0Ulp2TTB5ZkphZXNz
        QVFiUlJ3NlZnWjE3K0FRRU1wZFZSQUxwN0JSS2t4cTlreWdpRjJFUmJwUUZETndH
        blZFdWJPVER3M21ncFBXMDZ0aC94Vk1IVUNEYnN3bmFSQXBjR3RWVXdnM2c3L3Vq
        UktqNXduRE9veXdBWHRpaUFJa0dsSVdXSHBxZENtNjdqZzFNN3ZTVWdtbEpLRnp2
        cXdiQ2dPM3FocmhxNzF3QWtIR1lrOVI1YkxWQzVhM1lPUGo1aHA0Y2FGSW1VWURn
        SXdLWUo4QlFGWmViNW81K3QvQzdFTVVJVUI1T1RONzd5K09XZDgwN3MwSlBGd3p1
        VmpLSXBZWTZ0d0d0cnNLMWFDMUlvaHoxOGNsYytZT1J2SVJUZk1WUHRBM3paSnlk
        Mmk2SGlUcjBFc21VODJOMHZtSk1kUnRMZlpwU1puWnVDaXg2R1JVbWV5MXZRdlFi
        Vmxyd0xEY00vNjBQT3BSZzRFeGhFUGJlTW52elRGdWZ2T1BOa2hGbXVrN09hQQpI
        SFZGL3FUQnFyK2JvMktnWWFhNkpwMGJqU1JZS3RuMWNvSnNkMUpUS2VNCi0tLSBp
        VzlVMmExNnR4a2llRFhzemdyeGdETUdGdVh6QXlsQW44N213WFcrTHJZCj2WYGRV
        kB9P1l/kHCbMWj5v0MJ2dpPrTblHzWfJN+1hNvjFjVFuAcCs6SToZvXaF7lQ3/XB
        LeLFdKl6iFePgjo=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-14T17:30:51Z"
  mac: ENC[AES256_GCM,data:Co2e0PtVMx1ljD6tlG3fgbe/XgWfH31cvs1Jh6VkKR+PpkbkCMDZMN+DoWeoAcmMO3bd4aZs1mmOj5Au+SWj+EYq7kVlyh9cSt1afAPULm5jOeEW+LLLFl5HEikNi3WfNw2QYHXvTYmx++d16cxfbtrX2VtoUuG6TkgiFUA7iSI=,iv:Kj+SSNAkbytQoR65xPmnJu2AmfqWXilAIQWp2YcJMao=,tag:1Z/adi9MNxUO++KerjeKrg==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
