# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-cluster
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: garage-cluster
    template:
      data:
        GARAGE_ADMIN_TOKEN: "{{ .GARAGE_ADMIN_TOKEN }}"
        GARAGE_RPC_SECRET: "{{ .GARAGE_RPC_SECRET }}"
  dataFrom:
    - find:
        name:
          regexp: GARAGE.*
