# yaml-language-server: $schema=https://raw.githubusercontent.com/rajsinghtech/garage-operator/refs/heads/main/schemas/garagecluster_v1alpha1.json
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageCluster
metadata:
  name: garage
spec:
  replicas: 1
  replication:
    factor: 1
  zone: eu-west-1
  storage:
    metadata:
      size: 10Gi
    data:
      size: 100Gi
  network:
    rpcSecretRef:
      key: GARAGE_RPC_SECRET
      name: garage-cluster
  admin:
    adminTokenSecretRef:
      key: GARAGE_ADMIN_TOKEN
      name: garage-cluster
    enabled: true
  publicEndpoint:
    type: LoadBalancer
    loadBalancer:
      perNode: true
