apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: allow-default-access
  namespace: storage
spec:
  from:
    - kind: GarageKey
      namespace: default
    - kind: GarageBucket
      namespace: default

    - kind: GarageKey
      namespace: database
    - kind: GarageBucket
      namespace: database
  to:
    - kind: GarageCluster
      name: garage
