---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-bookarr
spec:
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ONBOARDING_CONFIG
      value: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            'config:recommended'
          ]
        }
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.database.svc.cluster.local:6379/2"
    - name: RENOVATE_AUTODISCOVER_FILTER
      value: "Faustvii/bookarr"
  image: ghcr.io/renovatebot/renovate:44.65.5@sha256:4e10f76a79f1c597f427f83c788a9f5b14a6295784c4cb68307b89b0a954abce
  parallelism: 10
  provider:
    name: github
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: "*/30 * * * *"
  secretRef: renovate-secret
  webhook:
    authentication:
      enabled: true
      secretRef:
        key: token
        name: renovate-webhook-token
    enabled: true
