---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-bookarr
spec:
  provider:
    name: github
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ONBOARDING_CONFIG
      value: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            'config:recommended'
          ]
        }
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.database.svc.cluster.local:6379/2"
    - name: RENOVATE_AUTODISCOVER_FILTER
      value: "Faustvii/bookarr"
  image: ghcr.io/renovatebot/renovate:44.14.10@sha256:26a4ced910d74c2d3dc8c1080b30704840f53206a3baede88fc579f37a2f6e45
  parallelism: 10
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: "*/30 * * * *"
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-webhook-token
        key: token
