---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github
spec:
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ONBOARDING_CONFIG
      value: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            'config:recommended'
          ]
        }
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.database.svc.cluster.local:6379/2"
    - name: RENOVATE_AUTODISCOVER_FILTER
      value: "!Faustvii/bookarr"
  image: ghcr.io/renovatebot/renovate:44.39.2@sha256:e6b93e709ca64495ab9307350b260064276ee02d15c6886387fd2d42c926623b
  parallelism: 10
  provider:
    name: github
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: "0 */3 * * *"
  secretRef: renovate-secret
  webhook:
    authentication:
      enabled: true
      secretRef:
        key: token
        name: renovate-webhook-token
    enabled: true
