---
# yaml-language-server: $schema=https://raw.githubusercontent.com/mogenius/renovate-operator/refs/heads/main/charts/renovate-operator/crd/renovate-operator.mogenius.com_renovatejobs.yaml
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github
spec:
  provider:
    name: github
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ONBOARDING_CONFIG
      value: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            'config:recommended'
          ]
        }
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.database.svc.cluster.local:6379/2"
  image: ghcr.io/renovatebot/renovate:43.86.1@sha256:c28712714c1c051b553d5566c9a5cfd04a8d08e208ece19a24e902de3041fa62
  parallelism: 10
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: "@hourly"
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-webhook-token
        key: token
