apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: truenas-smartctl
spec:
  selector:
    matchLabels:
      app: truenas-smartctl
  endpoints:
    - port: metrics
      interval: 60s
      path: /metrics
