---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app booklore
spec:
  chartRef:
    kind: OCIRepository
    name: booklore
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      booklore:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/faustvii/booklore
              tag: v2.2.3@sha256:c6dabcae4f079dd27ecf648a9be09feda1237d181034c4ea4ba8d4c65754d88f
            env:
              BOOKLORE_PORT: &port 6060
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    key: uri
                    name: booklore-postgres
              TZ: ${TZ}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi
    persistence:
      config:
        enabled: true
        existingClaim: *app
        advancedMounts:
          booklore:
            app:
              - path: /app/data
                subPath: app
      bookdrop:
        type: emptyDir
      library:
        type: emptyDir
      books:
        existingClaim: media-books-nfs-pvc
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
