---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/main/dist/schemas/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: ${APP}
spec:
  name: ${OIDC_APP_NAME}
  launchUrl: https://${APP}.${SECRET_DOMAIN}
  callbackUrls:
    - https://${APP}.${SECRET_DOMAIN}${OIDC_CALLBACK_PATH:=/oauth2/callback}
  logoutCallbackUrls:
    - https://${APP}.${SECRET_DOMAIN}${OIDC_LOGOUT_CALLBACK_PATH:=/logout}
  pkceEnabled: true
  allowedUserGroups:
    - name: ${APP}-users
    - name: ${APP}-admin-users
  secret:
    name: ${APP}-oidc-credentials
    keys:
      clientSecret: client-secret
      clientID: client-id
---
# yaml-language-server: $schema=https://schemas.web.garage.k8shub.tech/kaniop.rs/kanidmoauth2client_v1beta1.json
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: ${APP}
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  displayname: ${OIDC_APP_NAME}
  origin: https://${APP}.${SECRET_DOMAIN}
  redirectUrl:
    - https://${APP}.${SECRET_DOMAIN}${OIDC_CALLBACK_PATH:=/oauth2/callback}
  # Optionally add more fields (scopeMap, claimMap, etc) as needed
