---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ntfy
spec:
  chartRef:
    kind: OCIRepository
    name: ntfy
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault
    controllers:
      ntfy:
        type: statefulset
        statefulset:
          podManagementPolicy: Parallel
        containers:
          app:
            image:
              repository: binwiederhier/ntfy
              tag: v2.27.0@sha256:f2419f405127afa868f10985c1a41449e673477cee1eb19994339a5ae8b592e7
            args: ["serve"]
            env:
              NTFY_LOG_LEVEL: INFO
              TZ: ${TZ}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /v1/health
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 100Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true

    persistence:
      config:
        type: configMap
        enabled: true
        name: ntfy-configmap # overriden by kustomizeconfig
        globalMounts:
          - path: /etc/ntfy/server.yml
            subPath: server.yaml

      data:
        existingClaim: *app

      cache:
        type: emptyDir

    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 80

    service:
      app:
        controller: *app
        forceRename: *app
        ports:
          http:
            port: 80
            targetPort: *port
          metrics:
            port: 9090

    serviceMonitor:
      app:
        endpoints:
          - interval: 1m
            path: /metrics
            port: metrics
            scheme: http
            scrapeTimeout: 10s
        serviceName: *app
