apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:PzfsoUpnS1NNuZPrWqfytxu+g2rOdyZp+osOHoBgbiUUjuCm8W7H9nAuvOj9ScmOf9mGsDTWTs0r1pNCh7bsBX9voepDijMpY7oPZLIDHP3xq8bouARtb9GFS1l8qGBopq5NjHS/A1bRDe8/0XvKaENDxVgY1/DVizbb8zObD+wXs8iPFrhJ3N+uqh7ri1RCXnUhf+0PqwnJVlMdl532Jzh7jE3suGt331pLigEHV4rnG26I,iv:gimDtzMfyzXphFvVmm0ZdnZoH9X9nSae8oIJjxeHPr8=,tag:1gW1ieKN96oXF0RPRKf4ow==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybUtFTU1zVi83dk5ZVUZh
        dTFndnhCYWthd0h4c1IyaUZLODQ3bWR5bmtrCnlKNzhuNGpRUnZFa09jTC9rSDNE
        Q21KT1dUeU5keWd0eEJHdEZmMTIxNm8KLS0tIEJhZy9YZnllQUxqSEJ4THh2bk5X
        THJyMXR1ZjZvQ0NGcEJ3czJVT1pRNjAKGTxMhHc/5qjdp3vEqzbvJs2mlCLBwa/A
        JvBxwRM5dQihGHbPb9Qs7YQqqvlz9T/4VzJ32KSrMoxjD2+3idcjUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHZoNUs2dUhW
        Y0xmRk92MUhpaDJIZFpXS1NEMDIyQUhYV2pGOXJpWDZUUXFTcVFuVzI4NXJ3T0VG
        MW9vSjB2NjZWUkZlZk9FZ0wyeTBlaWw0NEZJdS9ZdmJmOXZKN2hoNkwvYWFpSm9y
        cjB5U1FiUE03d2VZWWZiU1FuRmtvQTV0TWcyczZhNDVGVmlJV0pKNnJQOXpmTmNl
        b3VsZk1OQzU2ZVFCTkw2N3dqYjNlcUM2RS9pWFNXdVcyd2djZys3aU1SbHUrS0tY
        Ly95eE5OeVNqanJTNHFjTHZENnJad1d1R3N3Uy9USmtYSVdrZU5RTHN3b2xRa1ZH
        NHMwdkNFd0RoVHB6OE9mMVZWTUFGcVRCeEtQMnVIOWZiQzNoYkNyT2NLak1ucDBV
        Y3VlMnlIK09ydXM5UkR6cjBPUXpVcEoycy8yN3RuaEVPRVVja01UaThCOFQ4VnRp
        VUc0UVYvdFZ6aEd4Mi9rRDJJWkp0SDVQTUJBRTBPVWEzWkFETXZuTlFCR2hwdi8w
        UDBRMlUyY01ybE1VVzgzcUs5aXdyV3JBZlcvZ3NyT1cxVmxkTm50cG1mNlNMZ2pI
        UXRXcER5UW1tTFRiSTMxdlJTcXlIWW1WL3puNjBvK2dsYmc1STBrajJZS3RwRHp2
        eFBYUjRYTG5PRytOUUgzNk5KK1VCSlFKNEtiQjVleVN4QTlkV1RMRENjODZOUWZW
        RVRreHU2OXNnUTlZdXRxTUc2UU1wRDBoSTZVdGdMYUgwQ3JWWkxoL1lWbzh3RzhR
        Y1gzc3gvUWU3T013OWw4UUtKT3N5UzQ1YVJ3SlJHeGNqcDVicnJDd2JjeXV5b25y
        K1VlTmNDaHRGUkdVQVlxZXBjbU1hRGZDQjFvWjh6TklTMzZjRTZ1NEp2VXNhTXhB
        bHQrTzE3T2RnbzVNT25idzArd095ZTlmdnU0T29OemtHR3pOMGM3Zm91WHc1d21a
        d3BFbVZGOTFHM1NGa0xzUjMyY09wTjgvQm1USHduQ09qc2hLY29PZjFJU2Q4QjYz
        UmZzWEdZMDJXRDJ6dmJVMlJtdmlTcU9lUWRMUVJLMFoyZ3hiQWlQeG1PY1JRMUF0
        aUNRVWk3b3ZjRjZnSkIrU3ZXazRvRkc1bkxaTGJqM1hJNTRBUCtTVmpCVm9GaXlF
        aGlFNU43eFBNdG5raVo4eThXNWFXUkFNNjNVaTRWSnA5SHJsZVNUWXJXZE55VEd2
        aUZublZNb3JLdzA4NC9tb1BndTY0T0kxRE1GRUlmL3J4cUR4QkE0MWpUQytkRDR4
        Tm1LL09iMDRIWUdKejdUNlZUaGFqWTNZOU9nNklHSys3YS95YitQSjBKdzd5cW9u
        Qkt5NGkzd3ZITzZ2ZURiaml5aXBiNEFad2Y0QmxTdHlwZWJIYzhtOFpDVEZOeHdI
        NWdNWGtzVWJIdC9BSzBnRDZBZ0ZNOXlxUG1MSTVPOFFFaFUzWkhmMU9wWHlFd1lS
        NFQwUGxEdXd0dk9iUVNNYXJvMUd5eUJlS3dSWGZDTFdrQWg2SHgzeU81MllIYVlK
        M01Zbm84VTJpbUMrVEgrKzFxYThkTlozdmpmU2RZTVllUmNZV20zOFZocFk1TEhp
        Uy9MSFZvMFBwUHZ4Z3BFR3UyanZLWXpjb2krcUFFcWFuRUJiaTI1YVFaaUtQaFQy
        cTk2YTNjMlQ2UklvKzB2blRobVRYdHZvckJRaWZnY1o2V0hVdWhmUjhwd1NoMTgv
        ZWU2bW5lbks0Qnd6RzNmQ1RESHBJUGo4MUQxRkpwaDhFTG5ZUmxweWZtYlk1S3U5
        WXFqR1Y1TjJLc3Y4MDBXRDJ4TEN2cXd2ZUhZeG5WNFR3eEFwVFZlb3hMaFAzOGRq
        dlBnTUtTemppTXd2WEdRbGFCVllrdDNlc2xVSTZlSUtkdUFLeThPV1BQaUhqRVNs
        RGZjc0ZEWVpaZWhJT0xYeWEyZnJFYnFaOFViYW0zUFBLUnNza1Q0ZVg0RWdBZwpw
        VldhVW0zd2J5eWxBNXBHeWdJOWFiR3JvaGhia21ZMEprdGRxVFdRcjFZCi0tLSBW
        TURRU1pxOTN0dFBPQ09vZlVyS3IxWlJ4KzM5TXBHUVZDWnBCOE5yazA4CutpOKBQ
        C0bB5KzjnN3rwTqEB2czhg3JfdhvyPQkWSlQmfXpbyNxgaclmJ+o0oacUW9oLdm8
        6iP/cJocfhq2X/U=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-08T16:10:50Z"
  mac: ENC[AES256_GCM,data:uK4hehwbm5A0ceuSRn82jOI1hP/QXQooIWsaia4xxruviHvL82GQwFsRPJsapvvlyiIZQH6mlz2xWYaQK3hgKrq2EqoyMlK3lSX5QaBL5sHqoNK1jehg8sJ9u6Li8sXS7rF05PA9t5JtyEfglKL+C2Sdygh65P0pVpzs4SkSrbI=,iv:rKhTfFUyPEIjSVoHj3IoSDf2GMcKlTsL7j8/knDVGn4=,tag:z3tQ4cnzf2BL+8gBTbsPUQ==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
