apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:PzfsoUpnS1NNuZPrWqfytxu+g2rOdyZp+osOHoBgbiUUjuCm8W7H9nAuvOj9ScmOf9mGsDTWTs0r1pNCh7bsBX9voepDijMpY7oPZLIDHP3xq8bouARtb9GFS1l8qGBopq5NjHS/A1bRDe8/0XvKaENDxVgY1/DVizbb8zObD+wXs8iPFrhJ3N+uqh7ri1RCXnUhf+0PqwnJVlMdl532Jzh7jE3suGt331pLigEHV4rnG26I,iv:gimDtzMfyzXphFvVmm0ZdnZoH9X9nSae8oIJjxeHPr8=,tag:1gW1ieKN96oXF0RPRKf4ow==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHprcW53L0Ix
        N0R3T08rWW1PMUpucitneFVSMDRyWmxjUW9HN1FqZG1UWGx4bys3SnFJRWFXeTh2
        NnBFY1FwSERiaTMrVWQySU9Ucnk2a1hWQ3ZSemhwWUNPZXRvTGM1cXdDTmpPTVVu
        K0JoV2NVc3pYNG5KamNlV1M5NnI2dkRiSCtmcE13YkV3azRuU0x6Wk9GNWRkUzVV
        U2h0QWVxZlRWYlNzaWcxZ0JBZWhKa25oZVNwRHEzZFdpMmhaYTV3eDFWbDVnQ2NO
        SGd6WFdIQnd2cnZJV0czVytCeDZMVlRIakZwM0pJem9GblV5VGF4VXlKR0NQcktT
        TndKcFZTOHhDYzZxVkhuNGZHcExwOUd1Z2NocTBuN1lxc2VRZEdncXpyc2YyREx3
        ZFozTzZyYmVkLzZRUFZXZThMdGJzNjFVVzI1MHFQaVN2dFdWc09PcVAvcUxWRDB6
        MEM4WWZYVVBCRmpFazR2aWlCRlIrSjJXbUwyNEFJNUVNTE9Wc2ZvRWIxbWx4ZFFK
        ZllwRkh5ZTFuWEo5Skx2ZWV3a0NoSnJtSkVkVThQVjcvRjZjSWc0OWNoT1FTU292
        dXFBK2FDbFBaZTBkY1lMYnZzUjlpdlJ6WS9BVVdsL3VLSjArWVpUcmxJUEIwUFcw
        RWlET2ZBMnhsVTR2N0RCRFNFTDgzT2E3VDgvODNNTS9TcUJJR2VsZG5BVFpRbDQ0
        cXM0S29oQVgyL3RabVdtcDJsc216bHdqSnltTkdWVjBHSUIxaHp6dUNtWXVZS2s3
        aUhSMmdqNGVJTGRJeEFnL1ZGY1NOTWNQZStSeUhXN014bTl5YnNKZFBzcEZGckRC
        RFJMajUzQlNyV0RBNGxqaCtSN0UzM2hIRFRhZXVOM0ZZNGZjTjlTMTJQMWNKS0Ir
        dG1hMWZEYzdiZjR0UTlOa1k1Z3RoaFVEamFBVTFwN3gwbHJZd2h6djhVTUpwWjVh
        a3JPY2lnQ0tuQmd3dXJ6b29GVDFaYmMzSTQ4K21UN0I5V1RmaU1NbFM2TC9hemZZ
        V2hTUHFEa081MGxBeWsrN2N4cmNqckdHc1ZVZG91YnF1emdPckFXVEZ3ZFZXM2Ev
        OHBUc2RibFdZUjdtc3NQY1lKZDRFLzcxMUw0NkVRL290RlFnUTVNcnRyV3dSaWVT
        Q0dFRzJIcHQ0MHk2M1NxZFhBQm15eEFKNkdFSldCMVRNY2VGemlEaWdXaWl1RndI
        TGZGUU9Lb2owLzM1R0pSNVRCaGw2bVgyd0dMVXpqbCsxKzA4d0Nwcy9PbWsyek9G
        ZTYyeG1rR2NSU255OU9ONnd6TmxVdWFrQlZBd0VOVFRuajRBQXFQUVJmb2pydits
        cHRQTXRwWm10VWd1Y28vVlpsa3B6dWxnV21CYWthTFI1K3RDbTl1bUlsNi9udkJ2
        dW9nVE1wWGVMeWc5Qmptb1hIT0ZObmY4QU5rODE2UnVxU05uSXE3N2hXMVYyMnd0
        ZjF3Rkh0UFQ2UGNqbUx3NzkxanNDMWluZHMzOTFqMXQ4UHVYTWhtZXFIcFNrc2V4
        Y2NheEhhTDY1SSsyLzl1RVVCb2lhc0UrSnVwREl4WVZSODNWNUI0MnA3aE9XY2tz
        QTNuaTF3NzdRc21UYm5ER0Y5QXAybnplcDQ2dmkwdkpaUklRS2tFbVBkTUJrY0xQ
        c2FpNTBrTk0yeUorY055LzdEeGpVdkhKQmhpRW5mcjFMeXhhMFAvRExoc2pCZkg1
        NnYxYlF4V3hmK0NCSENpU3dNcktHcm9FeXZjQjRCa1lPVEh3VDNtVGN0aXBhM1lN
        UHU4d3JjMlp0dDJCWjhJMW9HQzY3RERkaG5JcUZKNUdTTmxjSlkxaTd6Y0c2YXRY
        UVFtK2VuaFphQ1J1cFp1aVNIaFRhY2RSd0IwbnViMkFvSzMrM01zVVMwblVmWXZv
        QTU4UWdhUS9CTFArVm9wSVZFWlUraE9leHFZZGRpMEkvZVFDZ3QzWnA3NnZmZwpu
        NTBlTEdtdXNvNzZka3dIZUp1QWRtcktBVlRENEFJdGZnT1JpcFIwazk0Ci0tLSAy
        ek9EODd6U2Fua3h1TG9YVGJHZkhZVllhckVCMTl5aTFER3UxcUg3bXg4CjYqrOTm
        2ce+DwDrHESHTLXgmHUVnX86UVdF96B3d74lh69IbRyRQykmC4Yx1LjBzm2RYvZG
        M4qjHP8x5bXXsoE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-08T16:10:50Z"
  mac: ENC[AES256_GCM,data:uK4hehwbm5A0ceuSRn82jOI1hP/QXQooIWsaia4xxruviHvL82GQwFsRPJsapvvlyiIZQH6mlz2xWYaQK3hgKrq2EqoyMlK3lSX5QaBL5sHqoNK1jehg8sJ9u6Li8sXS7rF05PA9t5JtyEfglKL+C2Sdygh65P0pVpzs4SkSrbI=,iv:rKhTfFUyPEIjSVoHj3IoSDf2GMcKlTsL7j8/knDVGn4=,tag:z3tQ4cnzf2BL+8gBTbsPUQ==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
