---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/httproutefilter_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: static-status
spec:
  directResponse:
    contentType: application/json
    statusCode: 200
    body:
      type: Inline
      inline: |
        {
          "version": "9.9.9",
          "commitTag": "fded4a06c9de8a677622445a66e2898327c6f00d",
          "updateAvailable": false,
          "commitsBehind": 0,
          "restartRequired": false
        }
