apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker-registry-ghcr
spec:
  refreshInterval: "30m0s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: docker-registry-ghcr
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .github_ghcr_username }}",
                "password": "{{ .github_ghcr_token }}",
                "auth": "{{ printf \"%s:%s\" .github_ghcr_username .github_ghcr_token | b64enc }}"
              }
            }
          }
  dataFrom:
    - find:
        name:
          regexp: github_ghcr_.*
