apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:cGRNDWJByTlrv3gPw8U/ubiyCJ3KlHsivjQNtkYYAil00s9aIbe+7g==,iv:ecE136YXA0lyALjHQhr0n/PCBZgrfLiqnpMhQq6+vUU=,tag:H+YJacVVgWe51QzNzNAZqQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHJtUEkzYm1S
        TkI0SFlBdlhXdHgwRXB5SVRFMHhWR0V3MDlQaVU0VjdKS1RsV011a3NUOGhBQjky
        b2M3YVljRm5WcFlkeTdYVWhqTitHOWlQNXRra3hBK2E5dzBMcTdxQ3RFMUNMLzRG
        S21jYjRMb09PdDgrbEdsWHFXS0l4REZudURwY3E2UDZvUWw4YjJ5dC9mWHJsVjFT
        R2lYSlJOc1RyRnFNckw2QUo4Y0c2K243M2pFWGo4UkVuK3hzUm40cWIvQmhpYSs1
        ZmkrN2NHZ0x0RWdSaUR5U3lxaEtTamQ2ZVhIMlUxZ25vMEVEV0FkdFJyQjJTU3Qr
        M2tuNFhBa1psQS9RTUt3Wm1KeWlDSGxMTHZQaFg0N3l6aG9ETjRwQTB0bUVNTXZk
        bk14SUwwTzVLRkR3VzRiTXBvRmtWUE91dXU0eXB6NFQ0b2phcHltMEpJQi9KNnQ4
        K3JZbGxYUmNzUXB3aFhYbWcvLzdKZXBvcFYxUUprcGs1K0xWN2g3WVZDUzVINXFo
        NzM5SEh3bE9uT2VUNWY4blZ3ZG55Zk40VGl1dDN4MnUwYnB0aGhYbGplbkJScEY1
        aFhUcndsUVNycG9zYTdpSDhRV3JuM3prMStrejdYdnB1RlhQV0ZQVGxzVEU3VlFy
        VWZhbHpBZnFjRHc0NXkwaVVEUnhvMnJjYVkzOUhhc0gvM1grRHczc0ZWTE9yQW1X
        VjNrTGFzM0pmVXdUelNnSkFUL3FrQnB5c1h4UEdseVd5Mys3RS9IRXVJSm9OR2dP
        cjVXTUtKWHMwNHk4SnRmRS9IeXB6T2plbUhRbGt0M0x5R2pVY3JuZ1FDdW5Ydk8w
        QS9jOXRucEFpVXdHNk1zK0hFOW12QlJZTUpRVkkvZ0twOWgrM0l2K0pzbGxQMnFC
        K3VuM3VpNHNoU2hpdU1UTGR2VkM1SEhrWWhLRUx2VGd1WUIvSEowbGdUdE5KM2tL
        WCtnN3hhQktva09MRVZBdDVSZEpwQmE0YS9XeDE3NGUybU9VQU93M0hjMlFkeGdq
        bktSc1MrUXJNRUhqM0NZNTgrbGE0cnM0b0pSNkRzaEhHV3VsL1FTckNBb0FoZlE3
        QW9jS2RJTWlnTkdDMlQrNTBKZWIwc256dVp5MkI3cE5DT2RkRVpyeHlORjVCQnA1
        aktWQWN0eVU0bWcxNlptbXhock1pWkp2cUZMckpEN0RSYUliWjk0cXJGbmhuMFE3
        WmxySE8vQ29KMFVqak9vSkNoOGFnM3hvUm9QVDhSWTllSWFPdldMZkMxaHlnMW0r
        SmY4V2QvN3VwSWZOU3c1VEJGb0kweis0VE4zTldqenBuQmpqbXNPRURQUkg2WCtI
        d3lvVHk4S3pibHpkS2dIT3owbzN2a1AwZU1iNkU5SzdmYkJNcEg0QmZGVmkxTWFT
        Ly9TVlk2RTBHcVFpcmMrWE9pNXU2ZmJGd3l2a0pSUVI5bnJvNGJKV1RIb281Vk5Q
        aFN0Y0xDSEVTbC9XTjMxMDJGMUF3bFRmYU9mVnlvSVlRaklHUythSFFNdnlvUTF5
        Z0FhbDFIVHlrY2c0V21xQm1DMEJSUk0rWklrZWpaK0pqcDVGSkh2K2FaR0dNVFFG
        RC9PZXNraTZmQ3dnZnRWa2NuZkVXQXErWExWZW5YKzIzM2lld3dWaURQenM5cUdm
        dGwrWThIR3BIcFE1TU03YktZN2owWHB0S2hPV09FWnBxV1EzWnEvT042WTFDVnUy
        MTVyNUZTUFFVeS94Wkp2ZElJaFVjeVZ0Y3ZQeVlScjZnSm43KzBValQ4bFZsdDVw
        OVczR2pmaG5uL1BxeklheGNvbnM4Y1JmT0xQMkdLOHY0azFGdGZFN1RsYXE2Z041
        clNaTkQyVEJCSDVteHpjMjVLcnJCb3YvVFNDMk44V1FoLzBlUGtzbFJuaGNFTkVM
        QStrUzVLYnpHM0wwZnhyWVYxSW0vSm1RNmVVaHpJS25NbFBZQUxMeHZHTExldwpj
        TFQzZ3NaQVZLTTZPY3hJNTh2cFpvOVZwdmVHVis4dUNtS3g0TWJ4V2hvCi0tLSBz
        ZzFvU2E3Z2hFZnF6ek5Wem4rMEtDbTNPMVI5QTcvRjRuZ1c5UWpBTGs0Cl37F+ng
        dChe6kBzarlXDeLYRMqgYgr7+ZIyLxmAh2r2t1rjfVBAcJkBix6196FAcNrqthBW
        nPgS7fSQksVXBHk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-08T16:10:50Z"
  mac: ENC[AES256_GCM,data:L4IRCAbSs9S4GDxXtMQ+c/73q+mvFuFCZItVW6L4W8KIP9eezjF8YQ/iJ3vR1EhWQEVlmr/G19J4CbSZfXlpQNUaz5GB3iRT13Gt1DeDw6allalRG8ldYMCTX52GEftSM+/zohV+XZMon3rMH2GBXhNzNdABEZO55soeiU3k+NM=,iv:+4T4BiA5idUOI0KsmYJZ3uWKAuvTzQdwbiQfx7eldtQ=,tag:JC1gTrtk3tNVb/mXqDxH8A==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
