apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:cGRNDWJByTlrv3gPw8U/ubiyCJ3KlHsivjQNtkYYAil00s9aIbe+7g==,iv:ecE136YXA0lyALjHQhr0n/PCBZgrfLiqnpMhQq6+vUU=,tag:H+YJacVVgWe51QzNzNAZqQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ0k1NkM4Rk9PKzZWaENn
        T0NtMEQ0M0k2WDZ1ci81RGxHL3R6S2xGb1VvCkJ3RUZEazVjSGtTOG53WnVWdHd5
        RVAzNWE4cjJhL3ZSK2FZMDQ0bFZMcGcKLS0tIDAyMVoxNVZudkFGWGx2RWFMY1dP
        M29pYnptZmtxWW5meUpnZ2wyQmJLcGMKl+ucRr69Yx1wV5xGRWvBg4N6Jtbt1yj2
        21vPYPdizH8kQK1T1YAYYsYIKD9BCCadw6OZKGyD3KcK1p5Mjbzfpg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEQ2d1V3czkw
        MFphWFZ3YjJiV0Y5NHNMNWJtd2RnWlcraEZJRUUvUFJzRHc0djFRUkZicFBxNHNo
        anR6UzdQbFJtd2hHakp0Z0Fpa1ZmcExRM2JOU29YR25DMXNBRkZDZkZWbUpIcmxo
        eExhSDl5bEpJSmpQUW1jc2I2Z0dFTzJUTVl1dktJN1IvK2tuSkxRdklmTkV5a2Vv
        RXVyS0VJYUx5eWFZOHd1RnRLdnd1N1lEWjVVVFhsQUFxSEsvZkV5Z2k2ZjdvanlV
        b1cxcy80MkRiMm1DOTRFUmg2azdqS2MzeHBFL21BWElBbitPamhWYXBRd0ZLMGtn
        MEwzSG5kc2drMGt2MVYwYUZCSGdORFIzWWF1N25YSmpQRml5SDZXUHFhUFBYSUxS
        ZG02REw4c2cxc1VmQjZLQmd6OW16a0o4RkRHSnFxdUVib3ZsUHQxejMyc3pjcThp
        NldwYk9ibGltYmpuNnkwYkJQMnRvU0phc1NRR0Mxc0hZSkl6MFY2TE9PdVQ4alVw
        aUNBRHJXVTlNbkN0d25yWndPYnhITU12cWpwSEN3NXNXWHE5Z00rK3IwWWtLNUZ6
        OG5QV3RHbVJjczJIL04wRE9wWWxSaXp1ZXBtUFNRa2cxWnREdDlDK245UStlYmt6
        aDlqTzRwK1VONUpzc2cyNmRVNmZhMUp5M2NUSXNaNy8vcE5lWE5VS2lJZkQ2eDM4
        WEI5M0E2VERxQVdBYnBIaGJUUWhuZGhQWStoNXNUaGhwQzlWQ0hDMldOWHRvUFVw
        djNaU2FjdkQxNVMrcWtpMkttN05TclpVQ2xZSHQ0aGFsZE5yeHdxSnczVTArbytJ
        YUlGcms5eFhra1A2eHpIMjQwbmVzTnd5ZGlKR2tuTVBSVERwZUQrNlNuTTFkdGQ1
        K2tsZ09INHgvZjlyQkxZQzgyNHZpZHl0dmtlUHBCN0s1OUtLUmdCL3BkNHJ3THhu
        WnJJaWVpeXhWVkZTWjJVWlN2OEpjRmpJamsxcGZ0R3VuSWVFcmFoZmRsU2pDK1Ex
        akx2dVlrQjcvOUtyU040dVhoVnd1dGJJdXdMbmZ3eXpqcFp5M1J5Q21kMDRCQUtJ
        QlUweWFYTjBhM2N3YUJOMGVCWSsySm03ZzRYU1Y2THhJYTVjRWt4ek1hMnI4LzI2
        MVEvNm9RaGwvSzRnYVVnTEhwUUJNTisvRXhVRnZRYWhncmkvWTB4QjhyclJuNlh2
        WkhSeENYTjJlT3AvYmpNVHdTUGlHUU5xL3g1bm5vek5jdzNuK05xNTBETU9Sem1t
        QWQzMjZpVGNFRXlFZDlLREtzRXd6UkJ3aURBemUrM3c0eWtRQit4cjlFL1BTa0Jv
        Z3pRNGtaME1weHZkUUlpRWw2RXlYRGNlTGZpbHc2WEpZVjlUbFZUejBDN3BILzFN
        dmFuMCtwcUw5allPYWtGNlBnaDQ4TFNoVE8wUXlDWHVWVnIyQUYvVkRYS0wyRW0v
        dnhZR01SYXdEK3B4cmMzZWdwVktOc1U0WTRtRFlEeERKcjVpWjVUeFBXakVoS1Uv
        dHN1M2NwdnpvUGR3UHp6d2RHRkxrS2x4MDdNL1BFNWl2NWVMU1cwVk9SY3libHMy
        YjVKcGZVdXZEZHlDUTEzTlZDT2RuTTFHMm8vUGFuOEt5MXR5cUJGQ2dzUGN5WnlQ
        cUlrTUZrNUtwV3pUSXUzYmpKNkF1RE4wM0ZDNHVjMktkYlppbGNoUWVjRUFkYnlh
        WGpnYnE4ODh4dXhQdFNybFh2Snl5dUhUa0hUQ2RlL3ltNUs4Z09iVHhUYXBRTDRL
        VGR0TXAvcDlhWk00VFdZc0lhSStYRlluaHpRS1oyZ3ZsdGtFYkI4UkxZQWdyY25Z
        eGVrMHVCVFZaSEJaL0FUajY5dm9BK0hBNG9ORm9VTFVGK3pSZ3FLeHcxU2pvalBR
        ZHB0MExDRTRkc1lnNXEzY1JqMWkraWhCc0JDdm9CM3NjVmJPOGVOZFNxamtSZwp4
        cnVJSXpwSWxpTXkrOHgwVm5mbnhsUDRZKzY3Y0ExZHJHUFpTaDE1c3lJCi0tLSBL
        c3ZWRmFVYXo1VWJWL2hwaHFrTlNvc3pyM0dCUWFRVDlwbmlnc1BCR0k0CrI/gp4C
        uUZovtUbkfbRm/emHtD5BmPAanNP0SwjXVzsOKmS9p7vRr9s99yFgTmMnV18vQi7
        GWkGztad1BeFVsc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-08T16:10:50Z"
  mac: ENC[AES256_GCM,data:L4IRCAbSs9S4GDxXtMQ+c/73q+mvFuFCZItVW6L4W8KIP9eezjF8YQ/iJ3vR1EhWQEVlmr/G19J4CbSZfXlpQNUaz5GB3iRT13Gt1DeDw6allalRG8ldYMCTX52GEftSM+/zohV+XZMon3rMH2GBXhNzNdABEZO55soeiU3k+NM=,iv:+4T4BiA5idUOI0KsmYJZ3uWKAuvTzQdwbiQfx7eldtQ=,tag:JC1gTrtk3tNVb/mXqDxH8A==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
