---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.10.20:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.10.20"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-01"
    ipAddress: "192.168.10.10"
    nodeLabels:
      topology.kubernetes.io/gpus: amd
    installDiskSelector:
      serial: "S436NA0NA14981"
    machineSpec:
      secureboot: false
    controlPlane: true
    schematic:
      customization:
        extraKernelArgs:
          - pcie_aspm=off # Disable PCIe ASPM
          - talos.dashboard.disabled=1 # Disable Talos Dashboard
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu
            - siderolabs/drbd
            - siderolabs/nfsd
            - siderolabs/nut-client
            - siderolabs/zfs
    kernelModules:
      - name: zfs
      - name: amdgpu
        parameters:
          - ppfeaturemask=0xffffffff
      - name: dm_thin_pool
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
      - name: nbd
    patches:
      - "@./patches/storage/talos-01.yaml"
    networkInterfaces:
      - interface: bond0
        bond:
          deviceSelectors:
            - driver: igc
              hardwareAddr: "38:05:25:33:bb:*"
          mode: active-backup
        dhcp: false
        addresses:
          - "192.168.10.10/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.10.1"
        mtu: 1500
        vip:
          ip: "192.168.10.20"
        vlans:
          - vlanId: 90
            dhcp: false
  - hostname: "talos-02"
    ipAddress: "192.168.10.11"
    nodeLabels:
      topology.kubernetes.io/gpus: amd
    installDiskSelector:
      serial: "S436NA0NA18451"
    machineSpec:
      secureboot: false
    controlPlane: true
    schematic:
      customization:
        extraKernelArgs:
          - pcie_aspm=off # Disable PCIe ASPM
          - talos.dashboard.disabled=1 # Disable Talos Dashboard
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu
            - siderolabs/drbd
            - siderolabs/nfsd
            - siderolabs/nut-client
            - siderolabs/zfs
    kernelModules:
      - name: zfs
      - name: amdgpu
        parameters:
          - ppfeaturemask=0xffffffff
      - name: dm_thin_pool
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
      - name: nbd
    patches:
      - "@./patches/storage/talos-02.yaml"
    networkInterfaces:
      - interface: bond0
        bond:
          deviceSelectors:
            - driver: igc
              hardwareAddr: "38:05:25:36:ab:*"
          mode: active-backup
        dhcp: false
        addresses:
          - "192.168.10.11/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.10.1"
        mtu: 1500
        vip:
          ip: "192.168.10.20"
        vlans:
          - vlanId: 90
            dhcp: false
  - hostname: "talos-03"
    ipAddress: "192.168.10.12"
    nodeTaints:
      dedicated: "talos-03:NoSchedule"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    controlPlane: true
    schematic:
      customization:
        extraKernelArgs:
          - pcie_aspm=off # Disable PCIe ASPM
          - talos.dashboard.disabled=1 # Disable Talos Dashboard
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu
            - siderolabs/drbd
            - siderolabs/nfsd
            - siderolabs/nut-client
    kernelModules:
      - name: dm_thin_pool
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
      - name: nbd
    patches:
      - "@./patches/storage/talos-03.yaml"
      - "@./patches/global/talos-03-kubelet.yaml"
    networkInterfaces:
      - interface: bond0
        bond:
          deviceSelectors:
            - hardwareAddr: "00:a0:98:05:d4:96"
          mode: active-backup
        dhcp: false
        addresses:
          - "192.168.10.12/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.10.1"
        mtu: 1500
        vip:
          ip: "192.168.10.20"
        vlans:
          - vlanId: 90
            dhcp: false
  - hostname: "talos-04"
    ipAddress: "192.168.10.13"
    installDiskSelector:
      serial: "50026B73842AC0DD"
    machineSpec:
      secureboot: false
    nodeLabels:
      topology.kubernetes.io/gpus: amd
      node-role.kubernetes.io/rocm-worker: "true"
    controlPlane: false
    schematic:
      customization:
        extraKernelArgs:
          - pcie_aspm=off # Lower PCIe latency
          - amd_iommu=off # Strix Halo ROCm/iGPU compatibility
          - amd_pstate=active # AMD P-State driver
          - amdgpu.gttsize=126976 # AMD GPU GTT memory size
          - amdgpu.vm_fragment_size=8 # AMD GPU VM fragment size
          - ttm.pages_limit=32505856 # AMD GPU TTM memory limit
          - ttm.page_pool_size=25165824 # AMD GPU TTM page pool size
          - talos.dashboard.disabled=1 # Disable Talos Dashboard
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu
            - siderolabs/drbd
            - siderolabs/nfsd
            - siderolabs/nut-client
            - siderolabs/realtek-firmware
    kernelModules:
      - name: dm_thin_pool
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
      - name: nbd
    patches:
      - "@./patches/storage/talos-04.yaml"
      - "@./patches/global/talos-04-kubelet.yaml"
    networkInterfaces:
      - interface: bond0
        bond:
          interfaces:
            - enp97s0
          mode: active-backup
        dhcp: false
        addresses:
          - "192.168.10.13/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.10.1"
        mtu: 1500
        vip:
          ip: "192.168.10.20"
        vlans:
          - vlanId: 90
            dhcp: false

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-nut.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/machine-features.yaml"
