---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/oidc/kaniop-envoy
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
# patches:
#   - path: ./kanidmgroup.yaml
