---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-nfs-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
  nfs:
    path: ${NFS_PATH_DOWNLOADS}
    server: ${NFS_SERVER_IP}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: downloads-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-nfs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: downloads-nfs
