---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
  nfs:
    path: ${NFS_PATH_MEDIA}
    server: ${NFS_SERVER_IP}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: media-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-nfs-pv
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
  nfs:
    path: ${NFS_PATH_PLEXMEDIA}
    server: ${NFS_SERVER_IP}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plex-media-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-nfs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: plex-media-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-series-nfs-pv
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
  nfs:
    path: ${NFS_PATH_MEDIA_SERIES}
    server: ${NFS_SERVER_IP}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-series-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-series-nfs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: media-series-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies-nfs-pv
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
  nfs:
    path: ${NFS_PATH_MEDIA_MOVIES}
    server: ${NFS_SERVER_IP}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-movies-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies-nfs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: media-movies-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-books-nfs-pv
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
  nfs:
    path: ${NFS_PATH_MEDIA_BOOKS}
    server: ${NFS_SERVER_IP}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-books-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-books-nfs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: media-books-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-anime-nfs-pv
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
  nfs:
    path: ${NFS_PATH_MEDIA_ANIME}
    server: ${NFS_SERVER_IP}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-anime-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-anime-nfs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: media-anime-nfs
