apiVersion: kaniop.rs/v1beta1
kind: Kanidm
metadata:
  name: kanidm
spec:
  domain: idm.${SECRET_DOMAIN}
  tlsSecretName: kanidm-tls

  image: mirror.gcr.io/kanidm/server:1.10.1@sha256:146df93ce06984f1061bd7d29e27dcb6a4fcc939fca34bee9f8fcd4c5f5bba25

  replicaGroups:
    - name: default
      replicas: 1
      role: write_replica

  oauth2ClientNamespaceSelector: {}
  groupNamespaceSelector: {}
  personNamespaceSelector: {}
  serviceAccountNamespaceSelector: {}

  domainAppearance:
    displayName: "faust hub"

  storage:
    volumeClaimTemplate:
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 100Mi
