# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miroir
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: miroir
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    global:
      tolerations:
        - key: dedicated
          value: talos-03
          effect: NoSchedule
    replicaCount: 2
    monitoring:
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          matchLabels:
            dashboards: grafana
      podMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    nodes:
      talos-01:
        pools:
          repl:
            backend: zfs
            zfsDataset: tank/miroir
          local:
            backend: zfs
            zfsDataset: tank/miroir
      talos-02:
        pools:
          repl:
            backend: zfs
            zfsDataset: tank/miroir
          local:
            backend: zfs
            zfsDataset: tank/miroir
      talos-03:
        pools:
          local:
            backend: lvmthin
            device: /dev/disk/by-partlabel/r-miroir

    storageClasses:
      - name: miroir-replicated
        isDefault: false
        replicas: 2
        quorum: freeze
        pool: repl

      - name: miroir-local
        isDefault: false
        replicas: 1
        pool: local

    volumeSnapshotClasses:
      - name: miroir-snap
