apiVersion: v1
kind: Secret
metadata:
  name: universal-auth-credentials
type: Opaque
stringData:
  clientId: ENC[AES256_GCM,data:BKH9IUpKn5R+7vwqeefTyxmSp/GUF1H0G3FYVB+fgodCr9xN,iv:i0u+BTzPj2fbWNhlx2eVQf4AkK3i2AAVXWF/EKJbD/I=,tag:AfslX+l1LXqy9wbrUU5bmA==,type:str]
  clientSecret: ENC[AES256_GCM,data:KLOvRgep/g781lWup13cGqMw9TNCnCk1lTjKp0O5hvMGTnsXnD1NjdgvvYyuyp5Tzjpq1zY9ruVhfDJHLXs8dw==,iv:oyL8hKSilWxZ03Q3g3qZ/0V5sVue2xaxY/EgKXcLH+4=,tag:hHCgbEDLxLXBsnS5xfta5g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE9DQ0ZoR1hy
        Szl0ZTZnckdLYXlBdHlUVWpzVmJObEt6MERKdUhMUUk1TitielNIZmZvcW4rbEZu
        blBwdXc5QXcyclJxVDdDd0JFc0hmdWNzSVZsWHZSd3BQMnQxWG1ndVlYMW0rWEJ6
        YVdNK3p1VUZuZmtLaDJNNHJpNWhyQnRWbnAwc3k0U2xKTnZHMUZEVURKTVpqMDJC
        WFRtZ1NqdnpPdDZBRU45MTNXdHJBbFNkR2hvelpzY0l3OE85MlpsdjdSdW9ubU9L
        emxPYi94ZXZmRjQ2aG1JYXZVb3NYbzRIT2pSdEFlaEF2Q3g4d2xwS2Rab3Y1cWpa
        ZHl3OURCVmVhcmo0RGdSWmpJMUo3MTlPa09XbHFuN0trL1VObUc3SC9UanZIQ3hV
        NHAxR1lXWk0xTWQwYTluaHY0RHZXRHZ0QUk5R3BtV1F6YzdNdWFjSTdaVWQ3bzBK
        V1JVNW9KblltQWF6ZGZ0MUwwZU40RzVqKzRHNEkzYnQwR0Zab1NDdmFoMUxLUURi
        R1ZKaE14QmdwQXRSUE5SZk44QTlRc1FWdkVISFprQWpTNGNpdXFwR3AyZ3Zjdkph
        akJoK05Xblk3ODdNM0phYnBqbFJQNW5ZRkNiNVNrbmxzbU5UTWxqYm5SdURrSkdV
        QStiWEZ5NmN2bXV0KzZNT2ZMaTQxQVJQLzkwME83YVpBZVFockxFUTJHd2h3STM1
        dFdianRyd0x4cE80dGhBL1RKc0d1Zlh6UHBmWm5ObytlaUIvSGsvUUtzSW5qTXZC
        Mi94dXNPUlhWa295am9PbmdIaVdWUmxqWXVpSFRua3VLZUJnakZvN0N0cndjZ0dY
        cnFaVElrNldxcmlDNVRmS0dwdnByK3lwcFFucE1aODA4NXQ5ZnIrOEtaaEVYeDlM
        UVFLL0s0aVdNNEJYbHFvV095MksvcURVcjlGNFdxNU5rWWFjZys3YjV6WW8ybjZx
        aWFKYWpTY05uNlBlNmRFNWdLb2l1b0ZZV2orcHI3ZXg4TEw3NkdZYWFBNEZkd0FW
        byt2OE41SHppcVlpcC9aSVNDV2NtY3JGT0RKQ3MrVnhsQTMrOXFPQ0M2cWdNMWRR
        d3NCVENiWE9aNHZ2ZTdPTXJ1b1JqK0I0S2xQZzVTSE5JeWJBbTRDUnFDUUlnT0Nq
        RjI2Y2FScU9qWUR4UWIwWUtwYVBzVHc3czVMc3E2dERqZnNFNXF5L0hnRzRRdU1r
        eGdiRzhTMzU4NFdoMWFKRFFVTmhTVDJoNGVSdXpnaG9JRXNRZTBDTEt0aXBSeDlm
        MEgwNHZiT0tuM3hSOGpxdGR3T2YvcVc1TlZ5Y3ZMbGdqdzUrWStQTnd4dlJVVW5o
        SGZjeklENVhnV3duZFN5RFB1SVVkSW1qV2JyaGh1U012T0g2dzVZK0pVL1Y0OGdO
        bU1pUW52WGtwZWRSakltdGxQbHRFbXNUdXhMU1dybVlNK1g1b3NLaS9vckZxL0Zk
        Qmk4Sm1abm1OaUZCOWE5MjJob0hSdzNaOXVIQlpwYStWb09ybkdmRnlPL1ZQTkJ3
        Tk82ZU5NdDRhdmRyVlg2UDVOOC9Pd2kxLzFVY0xvcFkzQjc2dlFvTnhLVGR6N0lG
        UDNkclhnWk12NUJzbzBYbUlYRUFtemVFa1VWdUJHQXVENGxETU54UHNTZTZqckZh
        VDlNR3E4ZWloTm9QUUtiRjF5VWdOajZoL0dhT2phWmFyaVV5b0s0bmdqTWs2enJL
        RFI4V2psOXVseWVZbEY1TVFZY0p6a3ppMFlwMXJMMS80a2pacThmT1BNRmJCU01C
        M3FUcHMzWDQ2elVoenZObW1OZWdKK3VXdHR3VHF1Q0J0V3JOVmNNWlRFVkxBWG9L
        dVZvZFVaL2hVUThtMXRXMGxqRXhsaHpQcFdYR2tBeWJvTVFpdGdQMFMvWG5FV0xq
        bFdxcVlBOHpjdk1GQjZ0UVMrcUdIUUlVdlhmL3dRblEwR2dEMk0wZlFJWlJQZwp6
        WE16eUJydEVYTzQ5anNLTlN1dnVIYWVpQU1TUWhUUkp0RERpYllSbnpJCi0tLSB5
        Q0Q2MUI1Y3AzdUV2aW14OWI3VWgzbElvdDV2L0J2Z1ZFc2FueVdwQjc4CpChKWGR
        BGntLHAnIU7iIBYnfgw+qBtNzcRJ0qsvuG95ac6mkgtkddQ552gi33qOzowN1EFv
        sf/jh8nCmLXDaaI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-12-07T14:03:27Z"
  mac: ENC[AES256_GCM,data:ibGWWU9xHunQVTXPFu7NJy2IJWNSxiRxcIKaUjklNHUJ4ZrqYyueeKXqgSiK4qeyxMz0l5vjty8NBXQ8WvTH1cV//jjNpn5wNJF1jV5XZ98aFK/17oED7/mhmabL0Lce3l7aGif6IRTQz1ER+7BxVqtkjU0sf6xnQXFin2Au3E4=,iv:WrT36lSo1nDUW8NfWrT9wk07jmdw6oqUrjV1JGDaH2Q=,tag:XUacZEwP68WsgsVfVt18xg==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
