apiVersion: v1
kind: Secret
metadata:
  name: universal-auth-credentials
type: Opaque
stringData:
  clientId: ENC[AES256_GCM,data:BKH9IUpKn5R+7vwqeefTyxmSp/GUF1H0G3FYVB+fgodCr9xN,iv:i0u+BTzPj2fbWNhlx2eVQf4AkK3i2AAVXWF/EKJbD/I=,tag:AfslX+l1LXqy9wbrUU5bmA==,type:str]
  clientSecret: ENC[AES256_GCM,data:KLOvRgep/g781lWup13cGqMw9TNCnCk1lTjKp0O5hvMGTnsXnD1NjdgvvYyuyp5Tzjpq1zY9ruVhfDJHLXs8dw==,iv:oyL8hKSilWxZ03Q3g3qZ/0V5sVue2xaxY/EgKXcLH+4=,tag:hHCgbEDLxLXBsnS5xfta5g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHa0NSOVBiSXM0OFdyNkZu
        eGRrSEFROTN4bVRPL0ZRUE9KWnRIY05FS1VBCnptbDc2Q2JqZEtWQU9oSERYcXJI
        UEU5bWltK3hhaEZGT2dlZG1kSjhyalUKLS0tIHk2eUpjbmpSemh1SU56NFNXWXRT
        azRhYmtSakJQTHMrZHFsbElScVZVMWsKesbMVXvTGaNYGBY+qUwmwaQNAAs6SZQ+
        Sy9d1BaD04B/YPfZIeN4rJkN0m4PwPOBnGr9z4W1K7JhZbrL2W4lqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEFBcFdjSGlV
        R0diU29pYkxhMnNiazJxMXdLZ0p1bHByVnAyZitnSWZCQ3BQS2I0RnFTNWJhdmhk
        YVVJdGtQZmU2V3JMSml6L2JiZUtCZlJJZXV0bGZobFpPSjY4MnRnVHJGQWtnbisw
        VTFtTjVFM2FRbklzanJxUGFxOXRMMlV2c2RIeTYzOHhIckhodmVTbFVyamhlN1RQ
        dmZ2dmIzNEFGNkhOOEZtKzF3VG1HOGl1QnB4Tk8yQ3l1SHRsQW1UUWszZnhRYUo5
        R1FveFRDN2tVYkkzQmRMZjlzR1pBZXQySTRUNC9zMk1ndytPN0J5dDJwR1FUNys3
        ZVlaTm1jRE5FVVJSUlNLY2hxYXM2cWZjbDR4SU5Zam10NFplbHlHRUszTjFERkVR
        NHoyWE1FeldVTktPbHdONXVjUlIzWk8xMnVYR3NvYmVSSEhrWGVPR3NPM3JPNGIw
        SWlweERQN2V4T0N3aHd6VkFZUVl1N2lCako3ZXFPV1RaTXJnUW5hSmRjeHpmR294
        VDd4K0NKc3pUUlpqL1hvVXFFUEYzN05jaXFqOU83U2c3N3VTVzBMc3JORk90aWlN
        RTZpc2pMWDltQXNIYzQ1TGdYSml0SHdzanhXejArOG5YOU9aNnJ4dlNTK2hjbmI3
        UDY3d1oxL2g1YmVUMXNsdU5mSmRuaXdXcUZxcnBPQlZqVWNzcElIeHBBaXh1Ulcz
        djRSNDByejZNM0Zsays2Slo4czg1TXRndlREK0thT0VNUlh4ZXY4aVdRaDlOWkhq
        S0JKeXhralVaaS9yOGh2L1JNNVNMWjlUZE5tdk1UZENXS0k0c2NyQ2lXZXBiZW5H
        MmJuSlFlQ0U0SWpnZWh0eU9GVDNXWjhKUjdzeE1GOHFRa2NRdndlZUNYZTNaN1pa
        ZHhueHJTOFhZVDQ5SlZOVkJZelRtbWJ3Y0VsT0hKRENrajkvVnRFNlo1L3R5ZmtQ
        aVVxRmlxdUQ4SFNDdEQvVWx1MGJrNW9QZWtFaS9WTi9oWlRFMHRpbGV6K1VWVlBs
        YjdMZ1IyK2JSMnM4NkpMM1oxMDhVbjU0VHg4RXNZRVpyQkorcEpBQ1dVMCtjLzZj
        U1pyekZQTTlTUmRva2RMTlF0M2VaMjhxczlpLzBTSVhJdzdxOHo5VGs5dDRYVVVq
        ZlZkcnZnRG90NG9yN2hBWGh2UTF3dmo1Qyt2SXZnRnFkUVIzRGtRSk8vRzI2VVVR
        NDR1QWlFZ29VYW15aHFvK1hYVGJWbWRRdzU3eWpPcU5Tc2JKcmw5VkpWbUdCSGRo
        emRmUkhJYjd6bW41cFR2aWlnWUhKckZ4dUt0bzExV2RWM2RNY0h0Q3FublFvckRE
        SThibU5CbXRnVnF4ZUFmVXczRjlCbDZPdW9TL1FkZ3p3MEM1Z3lyWGtLb0pxY2hZ
        emhVSmdSeXkwaTMxUlN5blUxOVR6SEdrSFhWcC9ybndPc3FTQTZ3dHc5ZlQ2cEs5
        K1F6Z1MxMEFic1RLd1orcFp2bHZSVXVONkVBUisrSm9XYStkM2x4ZU1NMDNJME9q
        eTVLVXNLMm4zN0JKTDNmdHlwaENXTlptcVlZaE1sZ0Z3aVQwTzVVeUFLZEk4cVAw
        YjNEbHpMOTZid0pHZmVYcVhuYVhDVEdubEpyNWYrOE9DMUUxQlVqR3c5QjkyQUtu
        RGtSMlpjeFBrdHBwR2VqN2g1Rms1dm53LzZZdWJ6Tkp3c2dHeHRsVnkvQU54c0s4
        SU0xQWZPdURIbkNERWpqbmowdlJOdi9wT2FRTzBpcnI3cERMQ0l3NDQ4a3N4K2V2
        ZkxWTlIyV2xyTzJhelRXUGdUWWtrV3hnWFU4VnFQcVJBSjE5bXAxb0F1L1lKS1NE
        N01vUUMxQk5QanpQVjlyUC9adWpad0dIVVNlM3M5aFg4ZWFqcHhvM0NCdGdIZ2hu
        MllsZkVHNGtzWlZlajVhRzByL2JSQkRINnpxUGNueGVzeURyTWZWSjdlSmdhZwo2
        b3NadWtoVmZpYUpUWUhBUG1wZ05BQUJmTStjeG9Ucm1Icml5ZXFVTzFzCi0tLSBI
        SmVQT3UvM1YrbnRPQnpuWGptUjhFWDR3eStUajRFMjl4TXQ2OTVPYSs0CrYo5IZE
        XWjh4que8xp3VX/k1HLEJ/yXZ+8SLEicWgWl3KQAxfYyA3T4Q93CfjzHB1mAaM/o
        pHLXVsVwRPJGJ+s=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-12-07T14:03:27Z"
  mac: ENC[AES256_GCM,data:ibGWWU9xHunQVTXPFu7NJy2IJWNSxiRxcIKaUjklNHUJ4ZrqYyueeKXqgSiK4qeyxMz0l5vjty8NBXQ8WvTH1cV//jjNpn5wNJF1jV5XZ98aFK/17oED7/mhmabL0Lce3l7aGif6IRTQz1ER+7BxVqtkjU0sf6xnQXFin2Au3E4=,iv:WrT36lSo1nDUW8NfWrT9wk07jmdw6oqUrjV1JGDaH2Q=,tag:XUacZEwP68WsgsVfVt18xg==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
