---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../components/sops
  - ../../components/alerts
namespace: system-upgrade

resources:
  - ./namespace.yaml
  - ./tuppr/ks.yaml
