---
# yaml-language-server: $schema=https://raw.githubusercontent.com/rajsinghtech/garage-operator/refs/heads/main/schemas/garagebucket_v1alpha1.json
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: crd-schemas
spec:
  clusterRef:
    name: garage
    namespace: storage
  quotas:
    maxSize: 1Gi
  website:
    enabled: true
    indexDocument: index.html
