---
# yaml-language-server: $schema=https://raw.githubusercontent.com/rajsinghtech/garage-operator/refs/heads/main/schemas/garagekey_v1alpha1.json
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: crd-schemas-key
spec:
  clusterRef:
    name: garage
    namespace: storage
  bucketPermissions:
    - bucketRef: schemas
      read: true
      write: true
