---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - files:
      - conduit.toml=resources/conduit.toml
      - response.body=resources/client.json
    name: conduit-configmap
generatorOptions:
  disableNameSuffixHash: true
resources:
  # - gatus.yaml
  - ocirepository.yaml
  - externalsecret.yaml
  - helmrelease.yaml
  - httproutefilter.yaml
