apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: truenas
spec:
  endpoints:
    - interval: 60s
      path: /metrics
      port: smartctl-metrics
      relabelings:
        - replacement: truenas
          targetLabel: instance
      scrapeTimeout: 30s
    - interval: 30s
      path: /metrics
      port: node-exporter-metrics
      relabelings:
        - replacement: node-exporter
          targetLabel: job
  selector:
    matchLabels:
      app: truenas
