apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: truenas
spec:
  selector:
    matchLabels:
      app: truenas
  endpoints:
    - port: smartctl-metrics
      interval: 60s
      path: /metrics
    - port: node-exporter-metrics
      interval: 60s
      path: /metrics
