---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: booklore
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: pocket-id
      namespace: security
    - name: volsync
      namespace: storage
  interval: 1h
  path: ./kubernetes/apps/media/booklore/app
  postBuild:
    substitute:
      APP: booklore
      OIDC_APP_NAME: Booklore
      OIDC_CALLBACK_PATH: /oauth2-callback
      OIDC_LOGOUT_CALLBACK_PATH: /login
      OIDC_PROVIDER_LOGOUT_PATH: /logout
      VOLSYNC_CAPACITY: 15Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
