---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name bookarr-runner
spec:
  chartRef:
    kind: OCIRepository
    name: bookarr-runner
  interval: 1h
  values:
    containerMode:
      type: dind
    controllerServiceAccount:
      name: actions-runner-controller
      namespace: actions-runner-system
    githubConfigSecret: bookarr-runner-secret
    githubConfigUrl: https://github.com/Faustvii/bookarr
    maxRunners: 3
    minRunners: 0
    template:
      metadata:
        labels:
          runner: *name
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    runner: *name
                topologyKey: kubernetes.io/hostname
        containers:
          - command:
              - /home/runner/run.sh
            image: ghcr.io/home-operations/actions-runner:2.337.0@sha256:8b8e8326b5a08e658a0a41cfd2867afab69ca4194a152f986aa6fcd5430d09e7
            name: runner
        securityContext:
          fsGroup: 1001
          fsGroupChangePolicy: OnRootMismatch
        serviceAccountName: *name
        tolerations:
          - effect: NoSchedule
            key: dedicated
            operator: Equal
            value: talos-03
