---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: pw
spec:
  generator:
    passwordSpec:
      allowRepeat: true
      length: 64
      noUpper: false
      symbols: 0
  kind: Password
