---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: downflate-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: downflate-webhook-token-secret
    template:
      data:
        DOWNFLATE_GITHUB_APP_CLIENT_ID: "{{ .app_client_id }}"
        DOWNFLATE_GITHUB_APP_PRIVATE_KEY: "{{ .app_private_key }}"
        DOWNFLATE_WEBHOOK_SECRET: "{{ .DOWNFLATE_WEBHOOK_SECRET }}"
  dataFrom:
    - find:
        path: /downflate
    - find:
        path: /github-app
