apiVersion: v1alpha1
kind: KernelModuleConfig
name: dm_thin_pool
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: drbd
parameters:
  - usermode_helper=disabled
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: drbd_transport_tcp
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: nbd
