---
# yaml-language-server: $schema=https://raw.githubusercontent.com/rajsinghtech/garage-operator/refs/heads/main/schemas/garagebucket_v1beta1.json
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: postgres
spec:
  bucketId: caa4936288446c39ca1acb18130ed77140a0c55f02aa0ef09bb48dedf756a0c0
  clusterRef:
    name: garage
    namespace: storage
  quotas:
    maxSize: 50Gi
