---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage-store
spec:
  configuration:
    data:
      compression: gzip
    destinationPath: s3://postgres/
    endpointURL: http://garage.storage.svc.cluster.local:3900
    s3Credentials:
      accessKeyId:
        key: access-key-id
        name: postgres-key
      region:
        key: region
        name: postgres-key
      secretAccessKey:
        key: secret-access-key
        name: postgres-key
    wal:
      compression: zstd
  retentionPolicy: "10d"
