apiVersion: v1
kind: Secret
metadata:
  name: minio
type: Opaque
stringData:
  url: ENC[AES256_GCM,data:nCcRTFICwz3t85OCJcbVR52eN1sMhkEZGXbuRS4=,iv:hBgJQIwk8gH/EJYodiHH/KlDfLiKmslNV8DttE3L9cE=,tag:a4M5oVkI/XQnXmkmYXkN/A==,type:str]
  accessKey: ENC[AES256_GCM,data:LFA2nTkaksBEu3jg+maKghWINgU=,iv:AhAAqrebKLhixlfAQhq9pNBuOLMAF876yaJB6jnHHYo=,tag:tkR/hJm2TH4cZOV3C8CRVg==,type:str]
  secretKey: ENC[AES256_GCM,data:0WKWtQldERkLaBfwqqaocmRP6wG+w0nqYHO7fD4zHMNSCIeWQeDM3Q==,iv:pBHNqfgsqYcj3lKcJ1yH33sstuG7m3+txeab1g1m4eE=,tag:wFgRv82oauu3Mjw1HI7obg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOckt5YU5BUno5NlVlaHpZ
        QVc5dlF0ZkFkUTlZTld1MExDOE1SeVhob2hBCjZ4aGdzOWMwYVR0cDJKK1U5YlhK
        UERqbU9BelFCSXhhYlBVdmNoQzUxRXMKLS0tIHBBZllDdkdnTzJtMktzc0JTKzBp
        MHFSMU05Ynorb1E4Tk0ydVNBRmRBSGMK6X9zsQ1rzvtxOfwxzY+BlexuDklC2Ojf
        A5bzPpEN0K+TRNDvhYeNBb7Nr8Ls66PPLj+KG46DLBWDGBQVqPIAEQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGpXUHFOT0Vm
        SkV0U1pMMlBCdGx1WVowMW81QzBSUXpYak5tY0lrSHJNWFRkeWZZUExUMnkrMGFW
        WXpPeUgyaVh3QkFnYzd4Yy9aYS9xZFRBbFAwSXFrWVlXaUpsMTIzMzZuazZscmE4
        TUppME05NmFDZHZ0Rmd3aHcwd005M1JRMERLT2NuK0ZObWxmbVRnUngvNDF4cm5N
        YzZSelZEOVZSZ3RoQzl6blRzTUZzWDYxeEZzNm9oUFY5TkN2NGZqaHczNnI2VkRZ
        MnNBYVZiQmZpSDZ0V3hwTGRLQ05WODJ5RloxTnM4dGtJb3lBSlAwaFNMZXV5Y3Rx
        QlVyQkFyeDNRWEdNVVhINnJUMFNTeFlNWlNvOFYxRXRCck9ia0lFRzg5MEljVmxk
        SUVleHRiVS9lV3JvWFRGS2tUZDJWNDBMaDBBNEV6OWpYMzM0ZldjZEpBaVkxcWxQ
        bUNWeVUxalBUZ2ZjZDdsa1hmWXFST3c4UGMxZWJ3cmFKT2YwTlVPQmRyd2VsRTlJ
        QmhnRjh4NjIrQ0t0a3R4ZWRaZTJQOXEwQ0szcWFEUUYvb0E1WWwxTHFLODB5MHRK
        dWx5UWpqY1VWeFZPT1ZGaFlDU2E0Vnkzd1dTOEdiR3BzcjZET1VsRVdRNDlKNElQ
        VHBoQ0VQNWNaL0tIckxUTmxJR0hVdEVWc0pYWkpMdVhOSi9GSWdrSEEzbGtQTjNH
        ay9HNXJTWUdXRFBwTUZDcUZraUp5aUM2TFZaVGhvZGRKY3FlWWMyb1JRenRONDVP
        Zkg0S1FQTnY3ZGNwTG85aGdRVndnT0gycGJVejdLZUZsWkplcG1iUVIvUFJTWmRu
        bEE0OElFanJYRHJLbnZySDhTOSthdVIwcTdRVnZCRHpKWnNhM1Z4OHNkTUowWXlF
        Z2pLMlRNU0lLaDB0UWV2NG40MzNYdjJjMUFNY3RKZDMwNHF0bFgvelo0dXd2ZS9X
        SzBaQzdLNGtKNVVHVjIzMkRXdVYwSUJSNnRrYUVIMng5VDFhaE91VHVwRXFSeGVM
        TTgxRTZsdmNEMDlobGs4SW8xa2xLMk1KT3Fwb3NpS05VaW1XN0dmR3B3VmhWNmhG
        bVpWNlViU3VHYnprRXExU2lDRWQ1bDRvQ3dCMzJJYmVUYmk3bTRmZmxqY21QZTQ5
        RkhsQW9aamtIVXRrdndvT3B5MkVEa1pyY2ZkaWc3OGt6NWUrNGRHUlRQR1lQbWU5
        ZFlJSEtFNStmdjJ1V0VFdUU5Q1FVWFQ3KzFyOUg1ODR3em8zQUdFb3g5N0ZSVDRS
        NWRsOEZGdktoZDNVa08ycHIyUWYvRy9aeHVzM1pzZU1qTHRBWUJuNHBxSGRscTNF
        NGZvN0IvOEIydHFhdVlHbzlyQ2dsNFFjNEZlVmxLZ2hwMEVoblREaTFxTnVheUMv
        M3NKdG9VNVZrSVZmWTJJdGJrNmFpR2czb3A0SWtyUWpvcjkxTk1pU21qZ1NvQWNi
        L0M1MEZVSVEwcHZydjZCTnJyMVQwdW1sazJOUkt4ZVNHYTlsby9sWWNrU3dtVnBT
        Tmk4eC91b0NHZDZtMmNvYmJVNjNqWDYxbEVFZm15Y1N3QlFCSkJOSFVTWXh5MUJh
        bFpENFNTOUwydWhjelgrZENPZ3hoZVkyWFVKT1pRVlFRSEZYZS91SE9xbHpMYVE3
        UHZidFhiTjBIanBvcXA5NFZ2TDBSRWN1OG5Wb3VtaE5BRmVScmgzOGRPOGw1WnV4
        TkhER1hRTjN6YkplckZJa2ROT3Nwb0Z5RTVCanNPY2tKek94NmN4NVlkUHMxMTN1
        S0NkQTVQT1VyTjgzK1paK3RPRzJqcEZ2NlhQblhCeVlFUzlzTWxWdVBBbVNMZGdw
        c1RWMjM5Y2Jjc3FXNkxpVHhzdmV1V0dBM2o5bUQ0eDdoSG9pOVVsL2crWmp2b1cz
        bHU4RmdvMHRoYStnWWtpWld0NERZQVdVek0zVnIxWDdYRnF4TVBhK2dGU2JVZwpT
        SE1MZnpGa2JkZCtsV0pqR3JSWXY3c2hnODVIRDZUT05zeTBMa3l3V3l3Ci0tLSBP
        ak5UTm91ZERwYTFSN0lHRnE2WUFHRndWU0w5ajZmeXMzaVVaaTRSVGFnCncbL6Rx
        uKicRzgCOdkHoYM52YjaurQe8IiHIVY6guaZFVkvCNQg7t3FIsCYKUtxjFW7oyG4
        ipNRH6RhSO2f2Bc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-12-02T15:32:01Z"
  mac: ENC[AES256_GCM,data:FjFjVbQKslwnG5ZV5DJ1GAeiS/WaWF1/D9W/2FRtedHY6fAmq18nXxuzA13KPEHbdWQB8B/qaf/FhriuLbiScUhW9cTnMPaw9+BsbhPyNzs0ORKL/Vf8FIUd5I7dzmlDd7ztpo4lMJfhRz/QEb+Nh8w7gYSBSktV08yHp5LvngE=,iv:hkR3sdOIfGOFCA9SCmTZIG9DIXvrkCr6cigyeqcqF5M=,tag:mE6/dorHRekWqrQIBDwknw==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
