apiVersion: v1
kind: Secret
metadata:
  name: minio
type: Opaque
stringData:
  url: ENC[AES256_GCM,data:nCcRTFICwz3t85OCJcbVR52eN1sMhkEZGXbuRS4=,iv:hBgJQIwk8gH/EJYodiHH/KlDfLiKmslNV8DttE3L9cE=,tag:a4M5oVkI/XQnXmkmYXkN/A==,type:str]
  accessKey: ENC[AES256_GCM,data:LFA2nTkaksBEu3jg+maKghWINgU=,iv:AhAAqrebKLhixlfAQhq9pNBuOLMAF876yaJB6jnHHYo=,tag:tkR/hJm2TH4cZOV3C8CRVg==,type:str]
  secretKey: ENC[AES256_GCM,data:0WKWtQldERkLaBfwqqaocmRP6wG+w0nqYHO7fD4zHMNSCIeWQeDM3Q==,iv:pBHNqfgsqYcj3lKcJ1yH33sstuG7m3+txeab1g1m4eE=,tag:wFgRv82oauu3Mjw1HI7obg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IC9GdUVuRS8z
        UndEazhRRTk5TDFmckROZDFsR1NFS3NEUnhnb1R1TmpwTjlpcHc1a3BzZG9DbTJo
        MGxLaER1TUhNeXVvUFFYMlZyd3RkdWRtVitkamNZWk5JNHA3Z1JtMWVydTNzanMr
        RTRmWWUyaEVYdzdNRjRBT25RNTR5V0U1ZlR1bTRKSzBKNUdOTDdPV2J5VGcvOGIx
        c2ZZU0c2aENJcUV5OUhTT3Y0QkRqancwa2l3NHM5ME40VzVZZHRzeG1meFBxV081
        MHpHOVJIOUErOWlIWFhxZ3QyUDM0Tm1lbEZwTVVNdlZRWG96dTZaR3BpeGt2M0NJ
        NEdUanVnamN0MkUwbWFYTVZINXVUcFNDeVluTytBSk5xaWUrMzlOcUF6OTVTSk4r
        TkdSVEFKZ2hhWWNrVFJ5NmZoclVHTlRuK09xMUlrbFQ5Z2kvYzhWVm1qRHkvSWJ4
        ZmZ2dlFqVlQyd242RHRxMDhjTHZkT0I1YnV4OFNMME0vZzV1SThFVHBRRjNqa2xN
        ZGhoMklZYVZtVzJoZ0U3emlpRmlZbHdOZWllRGhoODlwL3AxSVlQM3lRVmZiNHBr
        dlhDMkdyY2kwMks0czV6cjNGQWE2dlBKQmNzbk01c0tMampKUkhNalZTWUozWVpF
        VGtRVUFsTHZDWXR3NkNnT2d6TWoycFhxVmNhcnZoQjJvSUZhS0psZlEwbTNIUm9N
        bFFIY2hET2kvVWFnNWtGeFpxVW1wS0RBWWZiekZTemZORldtNGZEdEZ3MGRNUmt0
        bCs1VFZ0cERBcTBUaHVJQXU0WG5CTWh6Qmd1amVFRWR5MWtaTVFGRmxPZUUvZXNq
        WDl6SDMyMER5a05MdFJsOEp5RkJrL05OSFJiTGNlaHA2M2Y3L3VxZyswclBjdWZo
        Szl4VTFwT0xYMkZJWFFkbnJ2YWRuMlMwLzh3dU1WZllwc1JESzJaL3FhbndydDhN
        R25LcmhlM093M2lKT2QxamFZWmUzeGdrd0Q3Z3M4Q3Q1QlJWYnNRUUNsVzlHQnNY
        QkQyUGtqdVdENCtLQ3poeGpiaXE2YmNCSGU3SEIxM3owUU1UckZkUTA5V2dSVkhO
        QjJxS254VTZoWnF5b1R6YXRJUnVVZTdWZXdzcmVpODBlMmZHR0IyK3dpYzdJUmM5
        Z01BaHhlME9NeVBrRTluVWszKzRmT0lVM1N2aENNOVhLaVVvTDl6RFRQdkVUSjhQ
        RUw4WkhvRSsyMzhPUmVpcG5SZHQzdlJ2MzlCdWt0bEFhUmE2VmM5azQ4OVJZTG1Z
        bWV4alBjWGJIaW9lYjVuakdpZEk2QkpTeC9DbjNTZ3lpSUZTOWl1d2d6K0FkWDVm
        alYwdnpkMVY2ZEhUMnlXOTlZRFVIVlUza1U4WTU5NnhPZityVk1XM3IvOFFLOVpI
        SlZJSEFyWE5HcDk2c2N0bW84YVZYT0o5STJVNGFTQkVNNis1dXdyVkRNSE4wSlZh
        RWpkWXk2MFlGSUNaZHdCS2lTU3dhVkJDQlFuOSs0T2xPT0hMRVIrTU9yRDQrSFhO
        SDNVRmtPaGNvU2ZFTytLTm1WRWlUSXJjZngrVktDRHZaSW1abG5acGhZWFhZbmNF
        WitTQzZPSC9FVmFER2g4V0pVSnBweFFSbTFzeHBoaHdZMnQxS0l5RVFveTlEV05i
        ZUs3czBlWGtSQ2FoQ240SDEzbGFPMlI2UlJNTnllU0FZd2U1bzZ5MWJaY2J4MUht
        eUR2alRGdnVueFVKOG85SnhiSU94djEvdW5uQU9DbkVPdjhFSFZPRTF2elFHS0ZE
        eHBkNHhYL0s2cGFVVUpIR3FuOE5IYXJ5NmVFZ3lHOEZiQjZGcU5nc0NNejRKZDk3
        QVlWWDc3UmtPaU1Id3h1S0lUZ2xEdjNvMkpPRE9sRkRvdHNtWG9GbU1kSkxpWGVH
        blNTNEJOOEJRakNBcWRKN1QxSUMvVTVjdGZkZ2VKRlpYUmhuLzBIelJNeFVIQQp3
        dGFSTlBNd000dkpCV2J1NTJpcCtFYmdyTHg0VndycFpuOGVJbndrYVBnCi0tLSBZ
        ZTNnWVlURHhZV3kxV3dmSzJja1prS3ExeTcyMmk0V3dLamhLL2IzQ1pzCj07uM81
        uRzSinvuxud3EbcL9pTW3AHGeOqjlRaVkXNSIhmXu1vZz7O/+p74yxkRYz87ksjT
        YCxWg0unkkbMisc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1l2pkptzteaqgxe9x7dg9025eeatcgmcspfs2f3s4xmrwsujehmenlv4q9cv6gamwuu8mfzt3clkxcfl32qe6sz87u2pez2w9g6txq586w8q2vvupwcx7p36w58fzdnkzfmqj8px9cyasr8qus37zd93j806cw5q8cyjvkfyv0mefd03tsht9ewa26yj3kxvj7me639vgrx3k50tqwx2wwf5jalyprf4vz6yazfh7c654qqtxxkc5rlq8ftcrslextyg6sg5p47xq4n4zv9q3xnc5j4n7vq7ze4wqnxf8qxh9cj38qcngw5jmddccp60fga9m5tdusz5hajy7cdumpuuvc93nrdsxfxw4wypfrvnheq43teresufruyqemrq44m6mry5yzz42wjn289pv0va2jc9px8cq6r9yxe3u7zt9xa94jw394gv2gh52qxwgx4truwaqh5t29ms4n3kmjs2kwswv4zu8xe4q6s48nv8sv0vfsm9vaf3xl4c3hgjm24thprfhdwmlsvphapy5ppthhyp0jfkykuvzlamaluwt8n28cv5kj3qq6w5hmekz0y5f6z9ncm6yjgnm8zglkkd37jkftmw858ucrseu2fxlezc89p9m4x7y9qakshk3dyc878ph87rzn0jrx8u7f354t233nm9kv8cslnuj2j58yme99v6n62s6933gwgfs2n5z4yskmfah2ce4v9cew2vmw7qryrcaq94vxav3hptsyew3ztjrhgqvr9thddyer0qeth432w5qgenhu9hsverguyu94rlu22tpzuf4s4dt4saqd0942w39k42jv2e02vuvqx4xdagvghduhc93kuz5lsrj64a3cvxtm0khg0y7vej6545j2w7y68n6k2wkf648tvjmywjqd35vqmqz62rt27vmf0r8q5685wcq2y5yl4g29pf5z6zlmfumcgu0e3dnkhwp8ydketlf2vzs85c58j6y846yx7kdngeevx75ccrmlky8g5vggn8tqzqhzzsu4e3c772uley5njl5gc3e2uhh0s4k686v6axp0zt0qvplwnp7zvdecugr0m4rgjvke3f3tdj3626x3k5vspj4klq6sc6dg7sv2rxtk3tnqumj49nnjpd42dpevqnfue94egqz9wz522lnsu0h0sujmljqdrmhc77358v2yy9rskeld2yn8hlvqanmg5a7jknzpfsx4ksxu37scnhx56f6gu0l3u9lltpxetqgp28049cpwsmvymyv2z9kkqayempf0fzv5pg385wtdz46fdkfj23s0x5sltpauwyn2u9f68s9vt96qt3xtf7nkzjappdf06f9gx9q2zm3npvhqku2p7npmle59k2tydqhhf72ma69nrfp37s4cgu0zuq3efnlg5ftmk4puafrqwxprf4aggdpgc46a3gs5z9rx5d4w273jdqmmnrn7h78r3s5wwe2j7tr8fgh329utgeh58eesfnl4shntslrpl97cmvhqpqpq6n0gavyst8r9f94sut4ktcepfc3ktx8lzvluyzy05rhrln5pcqnznpe5wrdxg5dekahzvu6gjzcs07v9s6349tkn9fmd8gsqqzwqqjrpvwcd65tek4g609vyslng3lhtx8ew5nfc365y69uwryqzx7c0yu0dyn2kl7fsws5wttmrv34y44ksr9n83n2zu9z8n984vhf2kltr5nfxtpkfxjy2detd0nydvcf6hqmctfmdy4esxkekuwphsjwyxeaq2u9c5s98rgzjhcmjj4hcedtw5ky7sfrffpe5tjmnx5pa67wfn4za7yg0eftvtyahs2gkvpp8yht5wsuyee44jjlq8a709ln3r3qrnvgy2wsnqwvqctn7pqryp06k6dyzvx365m7rd5nwxel6hydfurygftg92sgf55hc7jryyarxja5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-12-02T15:32:01Z"
  mac: ENC[AES256_GCM,data:FjFjVbQKslwnG5ZV5DJ1GAeiS/WaWF1/D9W/2FRtedHY6fAmq18nXxuzA13KPEHbdWQB8B/qaf/FhriuLbiScUhW9cTnMPaw9+BsbhPyNzs0ORKL/Vf8FIUd5I7dzmlDd7ztpo4lMJfhRz/QEb+Nh8w7gYSBSktV08yHp5LvngE=,iv:hkR3sdOIfGOFCA9SCmTZIG9DIXvrkCr6cigyeqcqF5M=,tag:mE6/dorHRekWqrQIBDwknw==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
